BEGIN
INSERT INTO observation_components (observation_id, component_id) VALUES (1109, 139);
INSERT INTO observation_components (observation_id, component_id) VALUES (1110, 139);
INSERT INTO observation_components (observation_id, component_id) VALUES (1111, 139);
INSERT INTO observation_components (observation_id, component_id) VALUES (1112, 139);
INSERT INTO observation_components (observation_id, component_id) VALUES (1113, 140);
INSERT INTO observation_components (observation_id, component_id) VALUES (1114, 140);
INSERT INTO observation_components (observation_id, component_id) VALUES (1115, 140);
INSERT INTO observation_components (observation_id, component_id) VALUES (1116, 140);
INSERT INTO observation_components (observation_id, component_id) VALUES (1117, 140);
INSERT INTO observation_components (observation_id, component_id) VALUES (1118, 140);
INSERT INTO observation_components (observation_id, component_id) VALUES (1119, 140);
INSERT INTO observation_components (observation_id, component_id) VALUES (1120, 140);
INSERT INTO observation_components (observation_id, component_id) VALUES (1121, 141);
INSERT INTO observation_components (observation_id, component_id) VALUES (1122, 141);
INSERT INTO observation_components (observation_id, component_id) VALUES (1123, 141);
INSERT INTO observation_components (observation_id, component_id) VALUES (1124, 141);
INSERT INTO observation_components (observation_id, component_id) VALUES (1125, 141);
INSERT INTO observation_components (observation_id, component_id) VALUES (1126, 141);
INSERT INTO observation_components (observation_id, component_id) VALUES (1127, 141);
INSERT INTO observation_components (observation_id, component_id) VALUES (1128, 141);
INSERT INTO observation_components (observation_id, component_id) VALUES (1129, 142);
INSERT INTO observation_components (observation_id, component_id) VALUES (1130, 142);
INSERT INTO observation_components (observation_id, component_id) VALUES (1131, 142);
INSERT INTO observation_components (observation_id, component_id) VALUES (1132, 142);
INSERT INTO observation_components (observation_id, component_id) VALUES (1133, 142);
INSERT INTO observation_components (observation_id, component_id) VALUES (1134, 142);
INSERT INTO observation_components (observation_id, component_id) VALUES (1135, 142);
INSERT INTO observation_components (observation_id, component_id) VALUES (1136, 142);
INSERT INTO observation_components (observation_id, component_id) VALUES (1137, 143);
INSERT INTO observation_components (observation_id, component_id) VALUES (1138, 143);
INSERT INTO observation_components (observation_id, component_id) VALUES (1139, 143);
INSERT INTO observation_components (observation_id, component_id) VALUES (1140, 143);
INSERT INTO observation_components (observation_id, component_id) VALUES (1141, 143);
INSERT INTO observation_components (observation_id, component_id) VALUES (1142, 143);
INSERT INTO observation_components (observation_id, component_id) VALUES (1143, 143);
INSERT INTO observation_components (observation_id, component_id) VALUES (1144, 143);
INSERT INTO observation_components (observation_id, component_id) VALUES (1145, 144);
INSERT INTO observation_components (observation_id, component_id) VALUES (1146, 144);
INSERT INTO observation_components (observation_id, component_id) VALUES (1147, 144);
INSERT INTO observation_components (observation_id, component_id) VALUES (1148, 144);
INSERT INTO observation_components (observation_id, component_id) VALUES (1149, 144);
INSERT INTO observation_components (observation_id, component_id) VALUES (1150, 144);
INSERT INTO observation_components (observation_id, component_id) VALUES (1151, 144);
INSERT INTO observation_components (observation_id, component_id) VALUES (1152, 144);
INSERT INTO observation_components (observation_id, component_id) VALUES (1153, 145);
INSERT INTO observation_components (observation_id, component_id) VALUES (1154, 145);
INSERT INTO observation_components (observation_id, component_id) VALUES (1155, 145);
INSERT INTO observation_components (observation_id, component_id) VALUES (1156, 145);
INSERT INTO observation_components (observation_id, component_id) VALUES (1157, 145);
INSERT INTO observation_components (observation_id, component_id) VALUES (1158, 145);
INSERT INTO observation_components (observation_id, component_id) VALUES (1159, 145);
INSERT INTO observation_components (observation_id, component_id) VALUES (1160, 145);
INSERT INTO observation_components (observation_id, component_id) VALUES (1161, 146);
INSERT INTO observation_components (observation_id, component_id) VALUES (1162, 146);
INSERT INTO observation_components (observation_id, component_id) VALUES (1163, 146);
INSERT INTO observation_components (observation_id, component_id) VALUES (1164, 146);
INSERT INTO observation_components (observation_id, component_id) VALUES (1165, 146);
INSERT INTO observation_components (observation_id, component_id) VALUES (1166, 146);
INSERT INTO observation_components (observation_id, component_id) VALUES (1167, 146);
INSERT INTO observation_components (observation_id, component_id) VALUES (1168, 146);
INSERT INTO observation_components (observation_id, component_id) VALUES (1169, 147);
INSERT INTO observation_components (observation_id, component_id) VALUES (1170, 147);
INSERT INTO observation_components (observation_id, component_id) VALUES (1171, 147);
INSERT INTO observation_components (observation_id, component_id) VALUES (1172, 147);
INSERT INTO observation_components (observation_id, component_id) VALUES (1173, 147);
INSERT INTO observation_components (observation_id, component_id) VALUES (1174, 147);
INSERT INTO observation_components (observation_id, component_id) VALUES (1175, 147);
INSERT INTO observation_components (observation_id, component_id) VALUES (1176, 147);
INSERT INTO observation_components (observation_id, component_id) VALUES (1177, 148);
INSERT INTO observation_components (observation_id, component_id) VALUES (1178, 148);
INSERT INTO observation_components (observation_id, component_id) VALUES (1179, 148);
INSERT INTO observation_components (observation_id, component_id) VALUES (1180, 148);
INSERT INTO observation_components (observation_id, component_id) VALUES (1181, 148);
INSERT INTO observation_components (observation_id, component_id) VALUES (1182, 148);
INSERT INTO observation_components (observation_id, component_id) VALUES (1183, 148);
INSERT INTO observation_components (observation_id, component_id) VALUES (1184, 148);
INSERT INTO observation_components (observation_id, component_id) VALUES (1185, 149);
INSERT INTO observation_components (observation_id, component_id) VALUES (1186, 149);
INSERT INTO observation_components (observation_id, component_id) VALUES (1187, 149);
INSERT INTO observation_components (observation_id, component_id) VALUES (1188, 149);
INSERT INTO observation_components (observation_id, component_id) VALUES (1189, 149);
INSERT INTO observation_components (observation_id, component_id) VALUES (1190, 149);
INSERT INTO observation_components (observation_id, component_id) VALUES (1191, 149);
INSERT INTO observation_components (observation_id, component_id) VALUES (1192, 149);
INSERT INTO observation_components (observation_id, component_id) VALUES (1193, 150);
INSERT INTO observation_components (observation_id, component_id) VALUES (1194, 150);
INSERT INTO observation_components (observation_id, component_id) VALUES (1195, 150);
INSERT INTO observation_components (observation_id, component_id) VALUES (1196, 150);
INSERT INTO observation_components (observation_id, component_id) VALUES (1197, 150);
INSERT INTO observation_components (observation_id, component_id) VALUES (1198, 150);
INSERT INTO observation_components (observation_id, component_id) VALUES (1199, 150);
INSERT INTO observation_components (observation_id, component_id) VALUES (1200, 150);
INSERT INTO observation_components (observation_id, component_id) VALUES (1201, 151);
INSERT INTO observation_components (observation_id, component_id) VALUES (1202, 151);
INSERT INTO observation_components (observation_id, component_id) VALUES (1203, 151);
INSERT INTO observation_components (observation_id, component_id) VALUES (1204, 151);
INSERT INTO observation_components (observation_id, component_id) VALUES (1205, 151);
INSERT INTO observation_components (observation_id, component_id) VALUES (1206, 151);
INSERT INTO observation_components (observation_id, component_id) VALUES (1207, 151);
INSERT INTO observation_components (observation_id, component_id) VALUES (1208, 151);
INSERT INTO observation_components (observation_id, component_id) VALUES (1209, 152);
INSERT INTO observation_components (observation_id, component_id) VALUES (1210, 152);
INSERT INTO observation_components (observation_id, component_id) VALUES (1211, 152);
INSERT INTO observation_components (observation_id, component_id) VALUES (1212, 152);
INSERT INTO observation_components (observation_id, component_id) VALUES (1213, 152);
INSERT INTO observation_components (observation_id, component_id) VALUES (1214, 152);
INSERT INTO observation_components (observation_id, component_id) VALUES (1215, 152);
INSERT INTO observation_components (observation_id, component_id) VALUES (1216, 152);
INSERT INTO observation_components (observation_id, component_id) VALUES (1217, 153);
INSERT INTO observation_components (observation_id, component_id) VALUES (1218, 153);
INSERT INTO observation_components (observation_id, component_id) VALUES (1219, 153);
INSERT INTO observation_components (observation_id, component_id) VALUES (1220, 153);
INSERT INTO observation_components (observation_id, component_id) VALUES (1221, 153);
INSERT INTO observation_components (observation_id, component_id) VALUES (1222, 153);
INSERT INTO observation_components (observation_id, component_id) VALUES (1223, 153);
INSERT INTO observation_components (observation_id, component_id) VALUES (1224, 153);
INSERT INTO observation_components (observation_id, component_id) VALUES (1225, 154);
INSERT INTO observation_components (observation_id, component_id) VALUES (1226, 154);
INSERT INTO observation_components (observation_id, component_id) VALUES (1227, 154);
INSERT INTO observation_components (observation_id, component_id) VALUES (1228, 154);
INSERT INTO observation_components (observation_id, component_id) VALUES (1229, 154);
INSERT INTO observation_components (observation_id, component_id) VALUES (1230, 154);
INSERT INTO observation_components (observation_id, component_id) VALUES (1231, 154);
INSERT INTO observation_components (observation_id, component_id) VALUES (1232, 154);
INSERT INTO observation_components (observation_id, component_id) VALUES (1233, 155);
INSERT INTO observation_components (observation_id, component_id) VALUES (1234, 155);
INSERT INTO observation_components (observation_id, component_id) VALUES (1235, 155);
INSERT INTO observation_components (observation_id, component_id) VALUES (1236, 155);
INSERT INTO observation_components (observation_id, component_id) VALUES (1237, 155);
INSERT INTO observation_components (observation_id, component_id) VALUES (1238, 155);
INSERT INTO observation_components (observation_id, component_id) VALUES (1239, 155);
INSERT INTO observation_components (observation_id, component_id) VALUES (1240, 155);
INSERT INTO observation_components (observation_id, component_id) VALUES (1241, 156);
INSERT INTO observation_components (observation_id, component_id) VALUES (1242, 156);
INSERT INTO observation_components (observation_id, component_id) VALUES (1243, 156);
INSERT INTO observation_components (observation_id, component_id) VALUES (1244, 156);
INSERT INTO observation_components (observation_id, component_id) VALUES (1245, 156);
INSERT INTO observation_components (observation_id, component_id) VALUES (1246, 156);
INSERT INTO observation_components (observation_id, component_id) VALUES (1247, 156);
INSERT INTO observation_components (observation_id, component_id) VALUES (1248, 156);
INSERT INTO observation_components (observation_id, component_id) VALUES (1249, 157);
INSERT INTO observation_components (observation_id, component_id) VALUES (1250, 157);
INSERT INTO observation_components (observation_id, component_id) VALUES (1251, 157);
INSERT INTO observation_components (observation_id, component_id) VALUES (1252, 157);
INSERT INTO observation_components (observation_id, component_id) VALUES (1253, 157);
INSERT INTO observation_components (observation_id, component_id) VALUES (1254, 157);
INSERT INTO observation_components (observation_id, component_id) VALUES (1255, 157);
INSERT INTO observation_components (observation_id, component_id) VALUES (1256, 157);
INSERT INTO observation_components (observation_id, component_id) VALUES (1257, 158);
INSERT INTO observation_components (observation_id, component_id) VALUES (1258, 158);
INSERT INTO observation_components (observation_id, component_id) VALUES (1259, 158);
INSERT INTO observation_components (observation_id, component_id) VALUES (1260, 158);
INSERT INTO observation_components (observation_id, component_id) VALUES (1261, 158);
INSERT INTO observation_components (observation_id, component_id) VALUES (1262, 158);
INSERT INTO observation_components (observation_id, component_id) VALUES (1263, 158);
INSERT INTO observation_components (observation_id, component_id) VALUES (1264, 158);
INSERT INTO observation_components (observation_id, component_id) VALUES (1265, 159);
INSERT INTO observation_components (observation_id, component_id) VALUES (1266, 159);
INSERT INTO observation_components (observation_id, component_id) VALUES (1267, 159);
INSERT INTO observation_components (observation_id, component_id) VALUES (1268, 159);
INSERT INTO observation_components (observation_id, component_id) VALUES (1269, 159);
INSERT INTO observation_components (observation_id, component_id) VALUES (1270, 159);
INSERT INTO observation_components (observation_id, component_id) VALUES (1271, 159);
INSERT INTO observation_components (observation_id, component_id) VALUES (1272, 159);
INSERT INTO observation_components (observation_id, component_id) VALUES (1273, 160);
INSERT INTO observation_components (observation_id, component_id) VALUES (1274, 160);
INSERT INTO observation_components (observation_id, component_id) VALUES (1275, 160);
INSERT INTO observation_components (observation_id, component_id) VALUES (1276, 160);
INSERT INTO observation_components (observation_id, component_id) VALUES (1277, 160);
INSERT INTO observation_components (observation_id, component_id) VALUES (1278, 160);
INSERT INTO observation_components (observation_id, component_id) VALUES (1279, 160);
INSERT INTO observation_components (observation_id, component_id) VALUES (1280, 160);
INSERT INTO observation_components (observation_id, component_id) VALUES (1281, 161);
INSERT INTO observation_components (observation_id, component_id) VALUES (1282, 161);
INSERT INTO observation_components (observation_id, component_id) VALUES (1283, 161);
INSERT INTO observation_components (observation_id, component_id) VALUES (1284, 161);
INSERT INTO observation_components (observation_id, component_id) VALUES (1285, 161);
INSERT INTO observation_components (observation_id, component_id) VALUES (1286, 161);
INSERT INTO observation_components (observation_id, component_id) VALUES (1287, 161);
INSERT INTO observation_components (observation_id, component_id) VALUES (1288, 161);
INSERT INTO observation_components (observation_id, component_id) VALUES (1289, 162);
INSERT INTO observation_components (observation_id, component_id) VALUES (1290, 162);
INSERT INTO observation_components (observation_id, component_id) VALUES (1291, 162);
INSERT INTO observation_components (observation_id, component_id) VALUES (1292, 162);
INSERT INTO observation_components (observation_id, component_id) VALUES (1293, 162);
INSERT INTO observation_components (observation_id, component_id) VALUES (1294, 162);
INSERT INTO observation_components (observation_id, component_id) VALUES (1295, 162);
INSERT INTO observation_components (observation_id, component_id) VALUES (1296, 162);
INSERT INTO observation_components (observation_id, component_id) VALUES (1297, 163);
INSERT INTO observation_components (observation_id, component_id) VALUES (1298, 163);
INSERT INTO observation_components (observation_id, component_id) VALUES (1299, 163);
INSERT INTO observation_components (observation_id, component_id) VALUES (1300, 163);
INSERT INTO observation_components (observation_id, component_id) VALUES (1301, 163);
INSERT INTO observation_components (observation_id, component_id) VALUES (1302, 163);
INSERT INTO observation_components (observation_id, component_id) VALUES (1303, 163);
INSERT INTO observation_components (observation_id, component_id) VALUES (1304, 163);
INSERT INTO observation_components (observation_id, component_id) VALUES (1305, 164);
INSERT INTO observation_components (observation_id, component_id) VALUES (1306, 164);
INSERT INTO observation_components (observation_id, component_id) VALUES (1307, 164);
INSERT INTO observation_components (observation_id, component_id) VALUES (1308, 164);
INSERT INTO observation_components (observation_id, component_id) VALUES (1309, 164);
INSERT INTO observation_components (observation_id, component_id) VALUES (1310, 164);
INSERT INTO observation_components (observation_id, component_id) VALUES (1311, 164);
INSERT INTO observation_components (observation_id, component_id) VALUES (1312, 164);
INSERT INTO observation_components (observation_id, component_id) VALUES (1313, 165);
INSERT INTO observation_components (observation_id, component_id) VALUES (1314, 165);
INSERT INTO observation_components (observation_id, component_id) VALUES (1315, 165);
INSERT INTO observation_components (observation_id, component_id) VALUES (1316, 165);
INSERT INTO observation_components (observation_id, component_id) VALUES (1317, 165);
INSERT INTO observation_components (observation_id, component_id) VALUES (1318, 165);
INSERT INTO observation_components (observation_id, component_id) VALUES (1319, 165);
INSERT INTO observation_components (observation_id, component_id) VALUES (1320, 165);
INSERT INTO observation_components (observation_id, component_id) VALUES (1321, 166);
INSERT INTO observation_components (observation_id, component_id) VALUES (1322, 166);
INSERT INTO observation_components (observation_id, component_id) VALUES (1323, 166);
INSERT INTO observation_components (observation_id, component_id) VALUES (1324, 166);
INSERT INTO observation_components (observation_id, component_id) VALUES (1325, 166);
INSERT INTO observation_components (observation_id, component_id) VALUES (1326, 166);
INSERT INTO observation_components (observation_id, component_id) VALUES (1327, 166);
INSERT INTO observation_components (observation_id, component_id) VALUES (1328, 166);
INSERT INTO observation_components (observation_id, component_id) VALUES (1329, 167);
INSERT INTO observation_components (observation_id, component_id) VALUES (1330, 167);
INSERT INTO observation_components (observation_id, component_id) VALUES (1331, 167);
INSERT INTO observation_components (observation_id, component_id) VALUES (1332, 167);
INSERT INTO observation_components (observation_id, component_id) VALUES (1333, 167);
INSERT INTO observation_components (observation_id, component_id) VALUES (1334, 167);
INSERT INTO observation_components (observation_id, component_id) VALUES (1335, 167);
INSERT INTO observation_components (observation_id, component_id) VALUES (1336, 167);
INSERT INTO observation_components (observation_id, component_id) VALUES (1337, 168);
INSERT INTO observation_components (observation_id, component_id) VALUES (1338, 168);
INSERT INTO observation_components (observation_id, component_id) VALUES (1339, 168);
INSERT INTO observation_components (observation_id, component_id) VALUES (1340, 168);
INSERT INTO observation_components (observation_id, component_id) VALUES (1341, 168);
INSERT INTO observation_components (observation_id, component_id) VALUES (1342, 168);
INSERT INTO observation_components (observation_id, component_id) VALUES (1343, 168);
INSERT INTO observation_components (observation_id, component_id) VALUES (1344, 168);
INSERT INTO observation_components (observation_id, component_id) VALUES (1345, 169);
INSERT INTO observation_components (observation_id, component_id) VALUES (1346, 169);
INSERT INTO observation_components (observation_id, component_id) VALUES (1347, 169);
INSERT INTO observation_components (observation_id, component_id) VALUES (1348, 169);
INSERT INTO observation_components (observation_id, component_id) VALUES (1349, 169);
INSERT INTO observation_components (observation_id, component_id) VALUES (1350, 169);
INSERT INTO observation_components (observation_id, component_id) VALUES (1351, 169);
INSERT INTO observation_components (observation_id, component_id) VALUES (1352, 169);
INSERT INTO observation_components (observation_id, component_id) VALUES (1353, 170);
INSERT INTO observation_components (observation_id, component_id) VALUES (1354, 170);
INSERT INTO observation_components (observation_id, component_id) VALUES (1355, 170);
INSERT INTO observation_components (observation_id, component_id) VALUES (1356, 170);
INSERT INTO observation_components (observation_id, component_id) VALUES (1357, 170);
INSERT INTO observation_components (observation_id, component_id) VALUES (1358, 170);
INSERT INTO observation_components (observation_id, component_id) VALUES (1359, 170);
INSERT INTO observation_components (observation_id, component_id) VALUES (1360, 170);
INSERT INTO observation_components (observation_id, component_id) VALUES (1361, 171);
INSERT INTO observation_components (observation_id, component_id) VALUES (1362, 171);
INSERT INTO observation_components (observation_id, component_id) VALUES (1363, 171);
INSERT INTO observation_components (observation_id, component_id) VALUES (1364, 171);
INSERT INTO observation_components (observation_id, component_id) VALUES (1365, 171);
INSERT INTO observation_components (observation_id, component_id) VALUES (1366, 171);
INSERT INTO observation_components (observation_id, component_id) VALUES (1367, 171);
INSERT INTO observation_components (observation_id, component_id) VALUES (1368, 171);
INSERT INTO observation_components (observation_id, component_id) VALUES (1369, 172);
INSERT INTO observation_components (observation_id, component_id) VALUES (1370, 172);
INSERT INTO observation_components (observation_id, component_id) VALUES (1371, 172);
INSERT INTO observation_components (observation_id, component_id) VALUES (1372, 172);
INSERT INTO observation_components (observation_id, component_id) VALUES (1373, 172);
INSERT INTO observation_components (observation_id, component_id) VALUES (1374, 172);
INSERT INTO observation_components (observation_id, component_id) VALUES (1375, 172);
INSERT INTO observation_components (observation_id, component_id) VALUES (1376, 172);
INSERT INTO observation_components (observation_id, component_id) VALUES (1377, 173);
INSERT INTO observation_components (observation_id, component_id) VALUES (1378, 173);
INSERT INTO observation_components (observation_id, component_id) VALUES (1379, 173);
INSERT INTO observation_components (observation_id, component_id) VALUES (1380, 173);
INSERT INTO observation_components (observation_id, component_id) VALUES (1381, 173);
INSERT INTO observation_components (observation_id, component_id) VALUES (1382, 173);
INSERT INTO observation_components (observation_id, component_id) VALUES (1383, 173);
INSERT INTO observation_components (observation_id, component_id) VALUES (1384, 173);
INSERT INTO observation_components (observation_id, component_id) VALUES (1385, 174);
INSERT INTO observation_components (observation_id, component_id) VALUES (1386, 174);
INSERT INTO observation_components (observation_id, component_id) VALUES (1387, 174);
INSERT INTO observation_components (observation_id, component_id) VALUES (1388, 174);
INSERT INTO observation_components (observation_id, component_id) VALUES (1389, 174);
INSERT INTO observation_components (observation_id, component_id) VALUES (1390, 174);
INSERT INTO observation_components (observation_id, component_id) VALUES (1391, 174);
INSERT INTO observation_components (observation_id, component_id) VALUES (1392, 174);
INSERT INTO observation_components (observation_id, component_id) VALUES (1393, 175);
INSERT INTO observation_components (observation_id, component_id) VALUES (1394, 175);
INSERT INTO observation_components (observation_id, component_id) VALUES (1395, 175);
INSERT INTO observation_components (observation_id, component_id) VALUES (1396, 175);
INSERT INTO observation_components (observation_id, component_id) VALUES (1397, 175);
INSERT INTO observation_components (observation_id, component_id) VALUES (1398, 175);
INSERT INTO observation_components (observation_id, component_id) VALUES (1399, 175);
INSERT INTO observation_components (observation_id, component_id) VALUES (1400, 175);
INSERT INTO observation_components (observation_id, component_id) VALUES (1401, 176);
INSERT INTO observation_components (observation_id, component_id) VALUES (1402, 176);
INSERT INTO observation_components (observation_id, component_id) VALUES (1403, 176);
INSERT INTO observation_components (observation_id, component_id) VALUES (1404, 176);
INSERT INTO observation_components (observation_id, component_id) VALUES (1405, 176);
INSERT INTO observation_components (observation_id, component_id) VALUES (1406, 176);
INSERT INTO observation_components (observation_id, component_id) VALUES (1407, 176);
INSERT INTO observation_components (observation_id, component_id) VALUES (1408, 176);
INSERT INTO observation_components (observation_id, component_id) VALUES (1409, 177);
INSERT INTO observation_components (observation_id, component_id) VALUES (1410, 177);
INSERT INTO observation_components (observation_id, component_id) VALUES (1411, 177);
INSERT INTO observation_components (observation_id, component_id) VALUES (1412, 177);
INSERT INTO observation_components (observation_id, component_id) VALUES (1413, 177);
INSERT INTO observation_components (observation_id, component_id) VALUES (1414, 177);
INSERT INTO observation_components (observation_id, component_id) VALUES (1415, 177);
INSERT INTO observation_components (observation_id, component_id) VALUES (1416, 177);
INSERT INTO observation_components (observation_id, component_id) VALUES (1417, 178);
INSERT INTO observation_components (observation_id, component_id) VALUES (1418, 178);
INSERT INTO observation_components (observation_id, component_id) VALUES (1419, 178);
INSERT INTO observation_components (observation_id, component_id) VALUES (1420, 178);
INSERT INTO observation_components (observation_id, component_id) VALUES (1421, 178);
INSERT INTO observation_components (observation_id, component_id) VALUES (1422, 178);
INSERT INTO observation_components (observation_id, component_id) VALUES (1423, 178);
INSERT INTO observation_components (observation_id, component_id) VALUES (1424, 178);
INSERT INTO observation_components (observation_id, component_id) VALUES (1425, 179);
INSERT INTO observation_components (observation_id, component_id) VALUES (1426, 179);
INSERT INTO observation_components (observation_id, component_id) VALUES (1427, 179);
INSERT INTO observation_components (observation_id, component_id) VALUES (1428, 179);
INSERT INTO observation_components (observation_id, component_id) VALUES (1429, 179);
INSERT INTO observation_components (observation_id, component_id) VALUES (1430, 179);
INSERT INTO observation_components (observation_id, component_id) VALUES (1431, 179);
INSERT INTO observation_components (observation_id, component_id) VALUES (1432, 179);
INSERT INTO observation_components (observation_id, component_id) VALUES (1433, 180);
INSERT INTO observation_components (observation_id, component_id) VALUES (1434, 180);
INSERT INTO observation_components (observation_id, component_id) VALUES (1435, 180);
INSERT INTO observation_components (observation_id, component_id) VALUES (1436, 180);
INSERT INTO observation_components (observation_id, component_id) VALUES (1437, 180);
INSERT INTO observation_components (observation_id, component_id) VALUES (1438, 180);
INSERT INTO observation_components (observation_id, component_id) VALUES (1439, 180);
INSERT INTO observation_components (observation_id, component_id) VALUES (1440, 180);
INSERT INTO observation_components (observation_id, component_id) VALUES (1441, 181);
INSERT INTO observation_components (observation_id, component_id) VALUES (1442, 181);
INSERT INTO observation_components (observation_id, component_id) VALUES (1443, 181);
INSERT INTO observation_components (observation_id, component_id) VALUES (1444, 181);
INSERT INTO observation_components (observation_id, component_id) VALUES (1445, 181);
INSERT INTO observation_components (observation_id, component_id) VALUES (1446, 181);
INSERT INTO observation_components (observation_id, component_id) VALUES (1447, 181);
INSERT INTO observation_components (observation_id, component_id) VALUES (1448, 181);
INSERT INTO observation_components (observation_id, component_id) VALUES (1449, 182);
INSERT INTO observation_components (observation_id, component_id) VALUES (1450, 182);
INSERT INTO observation_components (observation_id, component_id) VALUES (1451, 182);
INSERT INTO observation_components (observation_id, component_id) VALUES (1452, 182);
INSERT INTO observation_components (observation_id, component_id) VALUES (1453, 182);
INSERT INTO observation_components (observation_id, component_id) VALUES (1454, 182);
INSERT INTO observation_components (observation_id, component_id) VALUES (1455, 182);
INSERT INTO observation_components (observation_id, component_id) VALUES (1456, 182);
INSERT INTO observation_components (observation_id, component_id) VALUES (1457, 183);
INSERT INTO observation_components (observation_id, component_id) VALUES (1458, 183);
INSERT INTO observation_components (observation_id, component_id) VALUES (1459, 183);
INSERT INTO observation_components (observation_id, component_id) VALUES (1460, 183);
INSERT INTO observation_components (observation_id, component_id) VALUES (1461, 183);
INSERT INTO observation_components (observation_id, component_id) VALUES (1462, 183);
INSERT INTO observation_components (observation_id, component_id) VALUES (1463, 183);
INSERT INTO observation_components (observation_id, component_id) VALUES (1464, 183);
INSERT INTO observation_components (observation_id, component_id) VALUES (1465, 184);
INSERT INTO observation_components (observation_id, component_id) VALUES (1466, 184);
INSERT INTO observation_components (observation_id, component_id) VALUES (1467, 184);
INSERT INTO observation_components (observation_id, component_id) VALUES (1468, 184);
INSERT INTO observation_components (observation_id, component_id) VALUES (1469, 184);
INSERT INTO observation_components (observation_id, component_id) VALUES (1470, 184);
INSERT INTO observation_components (observation_id, component_id) VALUES (1471, 184);
INSERT INTO observation_components (observation_id, component_id) VALUES (1472, 184);
INSERT INTO observation_components (observation_id, component_id) VALUES (1473, 185);
INSERT INTO observation_components (observation_id, component_id) VALUES (1474, 185);
INSERT INTO observation_components (observation_id, component_id) VALUES (1475, 185);
INSERT INTO observation_components (observation_id, component_id) VALUES (1476, 185);
INSERT INTO observation_components (observation_id, component_id) VALUES (1477, 185);
INSERT INTO observation_components (observation_id, component_id) VALUES (1478, 185);
INSERT INTO observation_components (observation_id, component_id) VALUES (1479, 185);
INSERT INTO observation_components (observation_id, component_id) VALUES (1480, 185);
INSERT INTO observation_components (observation_id, component_id) VALUES (1481, 186);
INSERT INTO observation_components (observation_id, component_id) VALUES (1482, 186);
INSERT INTO observation_components (observation_id, component_id) VALUES (1483, 186);
INSERT INTO observation_components (observation_id, component_id) VALUES (1484, 186);
INSERT INTO observation_components (observation_id, component_id) VALUES (1485, 186);
INSERT INTO observation_components (observation_id, component_id) VALUES (1486, 186);
INSERT INTO observation_components (observation_id, component_id) VALUES (1487, 186);
INSERT INTO observation_components (observation_id, component_id) VALUES (1488, 186);
INSERT INTO observation_components (observation_id, component_id) VALUES (1489, 187);
INSERT INTO observation_components (observation_id, component_id) VALUES (1490, 187);
INSERT INTO observation_components (observation_id, component_id) VALUES (1491, 187);
INSERT INTO observation_components (observation_id, component_id) VALUES (1492, 187);
INSERT INTO observation_components (observation_id, component_id) VALUES (1493, 187);
INSERT INTO observation_components (observation_id, component_id) VALUES (1494, 187);
INSERT INTO observation_components (observation_id, component_id) VALUES (1495, 187);
INSERT INTO observation_components (observation_id, component_id) VALUES (1496, 187);
INSERT INTO observation_components (observation_id, component_id) VALUES (1497, 188);
INSERT INTO observation_components (observation_id, component_id) VALUES (1498, 188);
INSERT INTO observation_components (observation_id, component_id) VALUES (1499, 188);
INSERT INTO observation_components (observation_id, component_id) VALUES (1500, 188);
INSERT INTO observation_components (observation_id, component_id) VALUES (1501, 188);
INSERT INTO observation_components (observation_id, component_id) VALUES (1502, 188);
INSERT INTO observation_components (observation_id, component_id) VALUES (1503, 188);
INSERT INTO observation_components (observation_id, component_id) VALUES (1504, 188);
INSERT INTO observation_components (observation_id, component_id) VALUES (1505, 189);
INSERT INTO observation_components (observation_id, component_id) VALUES (1506, 189);
INSERT INTO observation_components (observation_id, component_id) VALUES (1507, 189);
INSERT INTO observation_components (observation_id, component_id) VALUES (1508, 189);
INSERT INTO observation_components (observation_id, component_id) VALUES (1509, 189);
INSERT INTO observation_components (observation_id, component_id) VALUES (1510, 189);
INSERT INTO observation_components (observation_id, component_id) VALUES (1511, 189);
INSERT INTO observation_components (observation_id, component_id) VALUES (1512, 189);
INSERT INTO observation_components (observation_id, component_id) VALUES (1513, 190);
INSERT INTO observation_components (observation_id, component_id) VALUES (1514, 190);
INSERT INTO observation_components (observation_id, component_id) VALUES (1515, 190);
INSERT INTO observation_components (observation_id, component_id) VALUES (1516, 190);
INSERT INTO observation_components (observation_id, component_id) VALUES (1517, 190);
INSERT INTO observation_components (observation_id, component_id) VALUES (1518, 190);
INSERT INTO observation_components (observation_id, component_id) VALUES (1519, 190);
INSERT INTO observation_components (observation_id, component_id) VALUES (1520, 190);
INSERT INTO observation_components (observation_id, component_id) VALUES (1521, 191);
INSERT INTO observation_components (observation_id, component_id) VALUES (1522, 191);
INSERT INTO observation_components (observation_id, component_id) VALUES (1523, 191);
INSERT INTO observation_components (observation_id, component_id) VALUES (1524, 191);
INSERT INTO observation_components (observation_id, component_id) VALUES (1525, 191);
INSERT INTO observation_components (observation_id, component_id) VALUES (1526, 191);
INSERT INTO observation_components (observation_id, component_id) VALUES (1527, 191);
INSERT INTO observation_components (observation_id, component_id) VALUES (1528, 191);
INSERT INTO observation_components (observation_id, component_id) VALUES (1529, 192);
INSERT INTO observation_components (observation_id, component_id) VALUES (1530, 192);
INSERT INTO observation_components (observation_id, component_id) VALUES (1531, 192);
INSERT INTO observation_components (observation_id, component_id) VALUES (1532, 192);
INSERT INTO observation_components (observation_id, component_id) VALUES (1533, 192);
INSERT INTO observation_components (observation_id, component_id) VALUES (1534, 192);
INSERT INTO observation_components (observation_id, component_id) VALUES (1535, 192);
INSERT INTO observation_components (observation_id, component_id) VALUES (1536, 192);
INSERT INTO demand_regions (region_id, region_name, demand_index, boundary) VALUES (1, 'New York Electronics Region', 91, MDSYS.SDO_GEOMETRY(2003,8307,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),MDSYS.SDO_ORDINATE_ARRAY(-74.6,40.3,-73.5,40.3,-73.5,41.2,-74.6,41.2,-74.6,40.3)));
INSERT INTO demand_regions (region_id, region_name, demand_index, boundary) VALUES (2, 'Chicago Electronics Region', 78, MDSYS.SDO_GEOMETRY(2003,8307,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),MDSYS.SDO_ORDINATE_ARRAY(-88.5,41.3,-87.4,41.3,-87.4,42.3,-88.5,42.3,-88.5,41.3)));
INSERT INTO trace_entities (entity_id, entity_key, display_name, entity_type, risk_score, risk_level, source_system, material_value, event_count, is_confirmed_defect, production_order_id, plant_id) VALUES (1, 'PO-8841', 'Production order 8841', 'production_order', 96, 'high', 'MES', 250, 3, 0, 8841, NULL);
INSERT INTO trace_entities (entity_id, entity_key, display_name, entity_type, risk_score, risk_level, source_system, material_value, event_count, is_confirmed_defect, production_order_id, plant_id) VALUES (2, 'PO-5077', 'Production order 5077', 'production_order', 91, 'high', 'MES', 250, 3, 0, 5077, NULL);
INSERT INTO trace_entities (entity_id, entity_key, display_name, entity_type, risk_score, risk_level, source_system, material_value, event_count, is_confirmed_defect, production_order_id, plant_id) VALUES (3, 'PO-1190', 'Production order 1190', 'production_order', 77, 'high', 'MES', 250, 3, 0, 1190, NULL);
INSERT INTO trace_entities (entity_id, entity_key, display_name, entity_type, risk_score, risk_level, source_system, material_value, event_count, is_confirmed_defect, production_order_id, plant_id) VALUES (4, 'LOT-SEMI-91A7', 'Semiconductor lot SEMI-91A7', 'material_lot', 94, 'high', 'QMS', 0, 3, 0, NULL, NULL);
INSERT INTO trace_entities (entity_id, entity_key, display_name, entity_type, risk_score, risk_level, source_system, material_value, event_count, is_confirmed_defect, production_order_id, plant_id) VALUES (5, 'MACHINE-ATE-017', 'Electrical test station 017', 'machine', 88, 'high', 'QMS', 0, 3, 0, NULL, NULL);
INSERT INTO trace_entities (entity_id, entity_key, display_name, entity_type, risk_score, risk_level, source_system, material_value, event_count, is_confirmed_defect, production_order_id, plant_id) VALUES (6, 'SUPPLIER-044', 'Semiconductor supplier 044', 'supplier', 62, 'medium', 'QMS', 0, 3, 0, NULL, NULL);
INSERT INTO trace_entities (entity_id, entity_key, display_name, entity_type, risk_score, risk_level, source_system, material_value, event_count, is_confirmed_defect, production_order_id, plant_id) VALUES (7, 'INSPECTION-0199', 'Electrical inspection 0199', 'inspection', 89, 'high', 'QMS', 0, 3, 0, NULL, NULL);
INSERT INTO trace_entities (entity_id, entity_key, display_name, entity_type, risk_score, risk_level, source_system, material_value, event_count, is_confirmed_defect, production_order_id, plant_id) VALUES (8, 'PLANT-001', 'SEER Edison Plant', 'plant', 30, 'low', 'QMS', 0, 3, 0, NULL, 1);
INSERT INTO trace_entities (entity_id, entity_key, display_name, entity_type, risk_score, risk_level, source_system, material_value, event_count, is_confirmed_defect, production_order_id, plant_id) VALUES (9, 'CERT-SEMI-91A7', 'Lot certificate SEMI-91A7', 'certificate', 70, 'high', 'QMS', 0, 3, 0, NULL, NULL);
INSERT INTO trace_entities (entity_id, entity_key, display_name, entity_type, risk_score, risk_level, source_system, material_value, event_count, is_confirmed_defect, production_order_id, plant_id) VALUES (10, 'LOT-SEMI-220', 'Semiconductor lot SEMI-220', 'material_lot', 25, 'low', 'QMS', 0, 3, 0, NULL, NULL);
INSERT INTO trace_entities (entity_id, entity_key, display_name, entity_type, risk_score, risk_level, source_system, material_value, event_count, is_confirmed_defect, production_order_id, plant_id) VALUES (11, 'MACHINE-SMT-003', 'SMT placement machine 003', 'machine', 35, 'low', 'QMS', 0, 3, 0, NULL, NULL);
INSERT INTO trace_entities (entity_id, entity_key, display_name, entity_type, risk_score, risk_level, source_system, material_value, event_count, is_confirmed_defect, production_order_id, plant_id) VALUES (12, 'INSPECTION-0200', 'Routine inspection 0200', 'inspection', 20, 'low', 'QMS', 0, 3, 0, NULL, NULL);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (1, 1, 4, 'USES_LOT', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (2, 2, 4, 'USES_LOT', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (3, 3, 4, 'USES_LOT', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (4, 4, 1, 'USED_IN_ORDER', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (5, 4, 2, 'USED_IN_ORDER', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (6, 4, 3, 'USED_IN_ORDER', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (7, 1, 5, 'PROCESSED_ON', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (8, 2, 5, 'PROCESSED_ON', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (9, 5, 1, 'PROCESSES_ORDER', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (10, 5, 2, 'PROCESSES_ORDER', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (11, 4, 6, 'SUPPLIED_BY', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (12, 6, 4, 'SUPPLIES_LOT', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (13, 1, 7, 'HAS_INSPECTION', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (14, 7, 1, 'INSPECTS_ORDER', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (15, 1, 8, 'AT_PLANT', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (16, 2, 8, 'AT_PLANT', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (17, 3, 8, 'AT_PLANT', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (18, 4, 9, 'HAS_CERTIFICATE', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (19, 9, 4, 'CERTIFIES_LOT', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (20, 3, 10, 'USES_LOT', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (21, 10, 3, 'USED_IN_ORDER', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (22, 3, 11, 'PROCESSED_ON', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (23, 3, 12, 'HAS_INSPECTION', 0.9, 1, 0);
INSERT INTO trace_relationships (relationship_id, from_entity, to_entity, relationship_type, strength, event_count, material_value) VALUES (24, 12, 3, 'INSPECTS_ORDER', 0.9, 1, 0);
INSERT INTO quality_cases (case_id, case_ref, case_type, status, risk_score, loss_amount, event_count) VALUES (1, 'SEER-QUALITY-001', 'shared_material_lot', 'open', 91, 0, 3);
INSERT INTO quality_cases (case_id, case_ref, case_type, status, risk_score, loss_amount, event_count) VALUES (2, 'SEER-QUALITY-002', 'shared_material_lot', 'open', 45, 0, 3);
INSERT INTO quality_case_entities (case_entity_id, case_id, entity_id, role, evidence_score) VALUES (1, 1, 1, 'review_seed', 80);
INSERT INTO quality_case_entities (case_entity_id, case_id, entity_id, role, evidence_score) VALUES (2, 1, 2, 'supporting_evidence', 80);
INSERT INTO quality_case_entities (case_entity_id, case_id, entity_id, role, evidence_score) VALUES (3, 1, 3, 'supporting_evidence', 80);
INSERT INTO quality_case_entities (case_entity_id, case_id, entity_id, role, evidence_score) VALUES (4, 1, 4, 'supporting_evidence', 80);
INSERT INTO quality_case_entities (case_entity_id, case_id, entity_id, role, evidence_score) VALUES (5, 1, 5, 'supporting_evidence', 80);
INSERT INTO quality_case_entities (case_entity_id, case_id, entity_id, role, evidence_score) VALUES (6, 1, 6, 'supporting_evidence', 80);
INSERT INTO quality_case_entities (case_entity_id, case_id, entity_id, role, evidence_score) VALUES (7, 1, 7, 'supporting_evidence', 80);
INSERT INTO quality_case_entities (case_entity_id, case_id, entity_id, role, evidence_score) VALUES (8, 2, 8, 'supporting_evidence', 80);
INSERT INTO quality_case_entities (case_entity_id, case_id, entity_id, role, evidence_score) VALUES (9, 2, 9, 'supporting_evidence', 80);
INSERT INTO quality_case_entities (case_entity_id, case_id, entity_id, role, evidence_score) VALUES (10, 2, 10, 'supporting_evidence', 80);
INSERT INTO work_centers (center_id, plant_id, name) VALUES (1, 1, 'Work center 1: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (2, 2, 'Work center 2: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (3, 3, 'Work center 3: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (4, 4, 'Work center 4: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (5, 5, 'Work center 5: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (6, 6, 'Work center 6: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (7, 7, 'Work center 7: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (8, 8, 'Work center 8: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (9, 9, 'Work center 9: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (10, 10, 'Work center 10: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (11, 11, 'Work center 11: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (12, 12, 'Work center 12: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (13, 13, 'Work center 13: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (14, 14, 'Work center 14: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (15, 15, 'Work center 15: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (16, 16, 'Work center 16: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (17, 1, 'Work center 17: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (18, 2, 'Work center 18: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (19, 3, 'Work center 19: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (20, 4, 'Work center 20: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (21, 5, 'Work center 21: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (22, 6, 'Work center 22: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (23, 7, 'Work center 23: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (24, 8, 'Work center 24: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (25, 9, 'Work center 25: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (26, 10, 'Work center 26: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (27, 11, 'Work center 27: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (28, 12, 'Work center 28: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (29, 13, 'Work center 29: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (30, 14, 'Work center 30: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (31, 15, 'Work center 31: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (32, 16, 'Work center 32: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (33, 1, 'Work center 33: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (34, 2, 'Work center 34: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (35, 3, 'Work center 35: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (36, 4, 'Work center 36: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (37, 5, 'Work center 37: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (38, 6, 'Work center 38: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (39, 7, 'Work center 39: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (40, 8, 'Work center 40: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (41, 9, 'Work center 41: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (42, 10, 'Work center 42: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (43, 11, 'Work center 43: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (44, 12, 'Work center 44: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (45, 13, 'Work center 45: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (46, 14, 'Work center 46: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (47, 15, 'Work center 47: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (48, 16, 'Work center 48: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (49, 1, 'Work center 49: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (50, 2, 'Work center 50: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (51, 3, 'Work center 51: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (52, 4, 'Work center 52: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (53, 5, 'Work center 53: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (54, 6, 'Work center 54: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (55, 7, 'Work center 55: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (56, 8, 'Work center 56: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (57, 9, 'Work center 57: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (58, 10, 'Work center 58: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (59, 11, 'Work center 59: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (60, 12, 'Work center 60: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (61, 13, 'Work center 61: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (62, 14, 'Work center 62: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (63, 15, 'Work center 63: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (64, 16, 'Work center 64: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (65, 1, 'Work center 65: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (66, 2, 'Work center 66: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (67, 3, 'Work center 67: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (68, 4, 'Work center 68: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (69, 5, 'Work center 69: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (70, 6, 'Work center 70: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (71, 7, 'Work center 71: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (72, 8, 'Work center 72: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (73, 9, 'Work center 73: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (74, 10, 'Work center 74: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (75, 11, 'Work center 75: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (76, 12, 'Work center 76: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (77, 13, 'Work center 77: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (78, 14, 'Work center 78: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (79, 15, 'Work center 79: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (80, 16, 'Work center 80: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (81, 1, 'Work center 81: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (82, 2, 'Work center 82: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (83, 3, 'Work center 83: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (84, 4, 'Work center 84: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (85, 5, 'Work center 85: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (86, 6, 'Work center 86: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (87, 7, 'Work center 87: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (88, 8, 'Work center 88: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (89, 9, 'Work center 89: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (90, 10, 'Work center 90: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (91, 11, 'Work center 91: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (92, 12, 'Work center 92: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (93, 13, 'Work center 93: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (94, 14, 'Work center 94: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (95, 15, 'Work center 95: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (96, 16, 'Work center 96: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (97, 1, 'Work center 97: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (98, 2, 'Work center 98: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (99, 3, 'Work center 99: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (100, 4, 'Work center 100: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (534, 5, 'Work center 534: SMT assembly');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (597, 6, 'Work center 597: electrical test');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (934, 7, 'Work center 934: module integration');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (387, 8, 'Work center 387: rework');
INSERT INTO work_centers (center_id, plant_id, name) VALUES (406, 9, 'Work center 406: SMT assembly');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (1, 1, 2, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (2, 2, 3, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (3, 3, 4, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (4, 4, 5, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (5, 5, 6, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (6, 6, 7, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (7, 7, 8, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (8, 8, 9, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (9, 9, 10, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (10, 10, 11, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (11, 11, 12, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (12, 12, 13, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (13, 13, 14, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (14, 14, 15, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (15, 15, 16, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (16, 16, 17, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (17, 17, 18, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (18, 18, 19, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (19, 19, 20, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (20, 20, 21, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (21, 21, 22, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (22, 22, 23, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (23, 23, 24, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (24, 24, 25, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (25, 25, 26, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (26, 26, 27, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (27, 27, 28, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (28, 28, 29, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (29, 29, 30, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (30, 30, 31, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (31, 31, 32, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (32, 32, 33, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (33, 33, 34, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (34, 34, 35, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (35, 35, 36, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (36, 36, 37, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (37, 37, 38, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (38, 38, 39, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (39, 39, 40, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (40, 40, 41, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (41, 41, 42, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (42, 42, 43, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (43, 43, 44, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (44, 44, 45, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (45, 45, 46, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (46, 46, 47, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (47, 47, 48, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (48, 48, 49, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (49, 49, 50, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (50, 50, 51, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (51, 51, 52, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (52, 52, 53, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (53, 53, 54, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (54, 54, 55, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (55, 55, 56, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (56, 56, 57, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (57, 57, 58, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (58, 58, 59, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (59, 59, 60, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (60, 60, 61, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (61, 61, 62, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (62, 62, 63, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (63, 63, 64, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (64, 64, 65, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (65, 65, 66, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (66, 66, 67, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (67, 67, 68, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (68, 68, 69, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (69, 69, 70, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (70, 70, 71, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (71, 71, 72, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (72, 72, 73, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (73, 73, 74, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (74, 74, 75, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (75, 75, 76, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (76, 76, 77, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (77, 77, 78, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (78, 78, 79, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (79, 79, 80, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (80, 80, 81, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (81, 81, 82, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (82, 82, 83, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (83, 83, 84, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (84, 84, 85, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (85, 85, 86, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (86, 86, 87, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (87, 87, 88, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (88, 88, 89, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (89, 89, 90, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (90, 90, 91, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (91, 91, 92, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (92, 92, 93, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (93, 93, 94, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (94, 94, 95, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (95, 95, 96, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (96, 96, 97, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (97, 97, 98, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (98, 98, 99, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (99, 99, 100, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (100, 100, 534, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (101, 534, 597, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (102, 597, 934, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (103, 934, 387, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (104, 387, 406, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (105, 406, 1, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (106, 934, 1, 75, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (107, 1, 2, 100, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (108, 2, 387, 125, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (109, 387, 934, 150, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (110, 934, 406, 175, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (111, 406, 597, 200, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (112, 597, 387, 25, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (113, 534, 934, 50, 'Synthetic component movement between work centers; return paths represent rework');
INSERT INTO material_transfers (transfer_id, from_center_id, to_center_id, quantity_units, description) VALUES (114, 387, 406, 75, 'Synthetic component movement between work centers; return paths represent rework');
COMMIT;


COMMIT;
END;
/
