SELECT c.COMPONENT_NAME, SUM(pol.LINE_TOTAL) AS total_material_value
FROM "LLUSER"."COMPONENTS" c
JOIN "LLUSER"."PRODUCTION_ORDER_LINES" pol ON c.COMPONENT_ID = pol.COMPONENT_ID
JOIN "LLUSER"."PRODUCTION_ORDERS" po ON pol.PRODUCTION_ORDER_ID = po.PRODUCTION_ORDER_ID
WHERE po.ORDER_STATUS IN ('released', 'in_production', 'completed')
GROUP BY c.COMPONENT_NAME
ORDER BY total_material_value DESC
FETCH FIRST 5 ROWS ONLY;
