CREATE TABLE plants (
  plant_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000000) NOT NULL,
  plant_name VARCHAR2(120) NOT NULL,
  city VARCHAR2(100) NOT NULL,
  state_province VARCHAR2(100) NOT NULL,
  latitude NUMBER NOT NULL,
  longitude NUMBER NOT NULL,
  location MDSYS.SDO_GEOMETRY NOT NULL,
  daily_capacity_units NUMBER NOT NULL,
  capacity_utilization_pct NUMBER NOT NULL,
  is_active NUMBER(1) NOT NULL,
  CONSTRAINT pk_plants PRIMARY KEY (plant_id),
  CONSTRAINT ck_plants_1 CHECK (latitude BETWEEN -90 AND 90),
  CONSTRAINT ck_plants_2 CHECK (longitude BETWEEN -180 AND 180),
  CONSTRAINT ck_plants_3 CHECK (daily_capacity_units > 0 AND daily_capacity_units = TRUNC(daily_capacity_units)),
  CONSTRAINT ck_plants_4 CHECK (capacity_utilization_pct BETWEEN 0 AND 100),
  CONSTRAINT ck_plants_5 CHECK (is_active IN (0,1))
);

CREATE TABLE components (
  component_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000000) NOT NULL,
  plant_id NUMBER NOT NULL,
  component_name VARCHAR2(160) NOT NULL,
  material_grade VARCHAR2(80) NOT NULL,
  process_route VARCHAR2(80) NOT NULL,
  category VARCHAR2(100) NOT NULL,
  subcategory VARCHAR2(100) NOT NULL,
  unit_cost NUMBER(12,2) NOT NULL,
  is_active NUMBER(1) NOT NULL,
  CONSTRAINT pk_components PRIMARY KEY (component_id),
  CONSTRAINT fk_components_1 FOREIGN KEY (plant_id) REFERENCES plants (plant_id),
  CONSTRAINT ck_components_1 CHECK (unit_cost >= 0),
  CONSTRAINT ck_components_2 CHECK (is_active IN (0,1))
);

CREATE TABLE customer_sites (
  customer_site_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000000) NOT NULL,
  site_name VARCHAR2(160) NOT NULL,
  first_name VARCHAR2(80) NOT NULL,
  last_name VARCHAR2(80) NOT NULL,
  email VARCHAR2(200) NOT NULL,
  priority_class VARCHAR2(30) NOT NULL,
  location MDSYS.SDO_GEOMETRY NOT NULL,
  requirements JSON NOT NULL,
  CONSTRAINT pk_customer_sites PRIMARY KEY (customer_site_id)
);

CREATE TABLE production_orders (
  production_order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000000) NOT NULL,
  customer_site_id NUMBER NOT NULL,
  plant_id NUMBER NOT NULL,
  scheduled_start DATE NOT NULL,
  due_date DATE NOT NULL,
  order_status VARCHAR2(30) NOT NULL,
  order_total NUMBER(12,2) NOT NULL,
  setup_cost NUMBER(12,2) NOT NULL,
  priority_score NUMBER,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_production_orders PRIMARY KEY (production_order_id),
  CONSTRAINT fk_production_orders_1 FOREIGN KEY (customer_site_id) REFERENCES customer_sites (customer_site_id),
  CONSTRAINT fk_production_orders_2 FOREIGN KEY (plant_id) REFERENCES plants (plant_id),
  CONSTRAINT ck_production_orders_1 CHECK (order_status IN ('planned','released','in_production','completed','cancelled','on_hold')),
  CONSTRAINT ck_production_orders_2 CHECK (due_date > scheduled_start),
  CONSTRAINT ck_production_orders_3 CHECK (scheduled_start = TRUNC(scheduled_start) AND due_date = TRUNC(due_date)),
  CONSTRAINT ck_production_orders_4 CHECK (order_total >= 0),
  CONSTRAINT ck_production_orders_5 CHECK (setup_cost >= 0),
  CONSTRAINT ck_production_orders_6 CHECK (priority_score BETWEEN 0 AND 100)
);

CREATE TABLE production_order_lines (
  order_line_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000000) NOT NULL,
  production_order_id NUMBER NOT NULL,
  component_id NUMBER NOT NULL,
  quantity NUMBER NOT NULL,
  unit_cost NUMBER(12,2) NOT NULL,
  line_total GENERATED ALWAYS AS (quantity * unit_cost) VIRTUAL,
  CONSTRAINT pk_production_order_lines PRIMARY KEY (order_line_id),
  CONSTRAINT fk_production_order_lines_1 FOREIGN KEY (production_order_id) REFERENCES production_orders (production_order_id),
  CONSTRAINT fk_production_order_lines_2 FOREIGN KEY (component_id) REFERENCES components (component_id),
  CONSTRAINT ck_production_order_lines_1 CHECK (quantity > 0 AND quantity = TRUNC(quantity)),
  CONSTRAINT ck_production_order_lines_2 CHECK (unit_cost >= 0)
);

CREATE TABLE quality_observations (
  observation_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000000) NOT NULL,
  customer_site_id NUMBER,
  observation_text VARCHAR2(4000) NOT NULL,
  defect_rate_pct NUMBER NOT NULL,
  inspected_units NUMBER NOT NULL,
  rejected_units NUMBER NOT NULL,
  rework_minutes NUMBER NOT NULL,
  downtime_minutes NUMBER NOT NULL,
  severity_score NUMBER NOT NULL,
  affected_orders NUMBER NOT NULL,
  corrective_actions_opened NUMBER NOT NULL,
  observed_at TIMESTAMP DEFAULT TIMESTAMP '2026-09-15 12:00:00' NOT NULL,
  CONSTRAINT pk_quality_observations PRIMARY KEY (observation_id),
  CONSTRAINT fk_quality_observations_1 FOREIGN KEY (customer_site_id) REFERENCES customer_sites (customer_site_id),
  CONSTRAINT ck_quality_observations_1 CHECK (defect_rate_pct BETWEEN 0 AND 100),
  CONSTRAINT ck_quality_observations_2 CHECK (inspected_units > 0 AND rejected_units BETWEEN 0 AND inspected_units AND rework_minutes >= 0),
  CONSTRAINT ck_quality_observations_3 CHECK (downtime_minutes >= 0),
  CONSTRAINT ck_quality_observations_4 CHECK (severity_score BETWEEN 0 AND 100),
  CONSTRAINT ck_quality_observations_5 CHECK (affected_orders >= 0 AND corrective_actions_opened >= 0)
);

CREATE TABLE observation_components (
  observation_id NUMBER NOT NULL,
  component_id NUMBER NOT NULL,
  CONSTRAINT pk_observation_components PRIMARY KEY (observation_id, component_id),
  CONSTRAINT fk_observation_components_1 FOREIGN KEY (observation_id) REFERENCES quality_observations (observation_id),
  CONSTRAINT fk_observation_components_2 FOREIGN KEY (component_id) REFERENCES components (component_id)
);

CREATE TABLE component_embeddings (
  component_id NUMBER NOT NULL,
  embedding VECTOR(384) NOT NULL,
  CONSTRAINT pk_component_embeddings PRIMARY KEY (component_id),
  CONSTRAINT fk_component_embeddings_1 FOREIGN KEY (component_id) REFERENCES components (component_id)
);

CREATE TABLE demand_regions (
  region_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000000) NOT NULL,
  region_name VARCHAR2(120) NOT NULL,
  demand_index NUMBER NOT NULL,
  boundary MDSYS.SDO_GEOMETRY NOT NULL,
  CONSTRAINT uq_demand_regions_region_name UNIQUE (region_name),
  CONSTRAINT pk_demand_regions PRIMARY KEY (region_id),
  CONSTRAINT ck_demand_regions_1 CHECK (demand_index BETWEEN 0 AND 100)
);

CREATE TABLE trace_entities (
  entity_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000000) NOT NULL,
  entity_key VARCHAR2(100) NOT NULL,
  display_name VARCHAR2(160) NOT NULL,
  entity_type VARCHAR2(30) NOT NULL,
  risk_score NUMBER NOT NULL,
  risk_level VARCHAR2(20) NOT NULL,
  source_system VARCHAR2(30) NOT NULL,
  material_value NUMBER(12,2) NOT NULL,
  event_count NUMBER NOT NULL,
  is_confirmed_defect NUMBER(1) NOT NULL,
  production_order_id NUMBER,
  plant_id NUMBER,
  CONSTRAINT uq_trace_entities_entity_key UNIQUE (entity_key),
  CONSTRAINT pk_trace_entities PRIMARY KEY (entity_id),
  CONSTRAINT fk_trace_entities_1 FOREIGN KEY (production_order_id) REFERENCES production_orders (production_order_id),
  CONSTRAINT fk_trace_entities_2 FOREIGN KEY (plant_id) REFERENCES plants (plant_id),
  CONSTRAINT ck_trace_entities_1 CHECK (entity_type IN ('production_order','material_lot','supplier','inspection','certificate','machine','plant')),
  CONSTRAINT ck_trace_entities_2 CHECK (risk_score BETWEEN 0 AND 100),
  CONSTRAINT ck_trace_entities_3 CHECK (risk_level IN ('low','medium','high')),
  CONSTRAINT ck_trace_entities_4 CHECK (material_value >= 0 AND event_count >= 0),
  CONSTRAINT ck_trace_entities_5 CHECK (is_confirmed_defect IN (0,1))
);

CREATE TABLE trace_relationships (
  relationship_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000000) NOT NULL,
  from_entity NUMBER NOT NULL,
  to_entity NUMBER NOT NULL,
  relationship_type VARCHAR2(60) NOT NULL,
  strength NUMBER NOT NULL,
  event_count NUMBER NOT NULL,
  material_value NUMBER(12,2) NOT NULL,
  CONSTRAINT pk_trace_relationships PRIMARY KEY (relationship_id),
  CONSTRAINT fk_trace_relationships_1 FOREIGN KEY (from_entity) REFERENCES trace_entities (entity_id),
  CONSTRAINT fk_trace_relationships_2 FOREIGN KEY (to_entity) REFERENCES trace_entities (entity_id),
  CONSTRAINT ck_trace_relationships_1 CHECK (strength BETWEEN 0 AND 1),
  CONSTRAINT ck_trace_relationships_2 CHECK (event_count > 0 AND material_value >= 0)
);

CREATE TABLE quality_cases (
  case_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000000) NOT NULL,
  case_ref VARCHAR2(80) NOT NULL,
  case_type VARCHAR2(40) NOT NULL,
  status VARCHAR2(30) NOT NULL,
  risk_score NUMBER NOT NULL,
  loss_amount NUMBER(12,2) NOT NULL,
  event_count NUMBER NOT NULL,
  CONSTRAINT uq_quality_cases_case_ref UNIQUE (case_ref),
  CONSTRAINT pk_quality_cases PRIMARY KEY (case_id),
  CONSTRAINT ck_quality_cases_1 CHECK (risk_score BETWEEN 0 AND 100),
  CONSTRAINT ck_quality_cases_2 CHECK (loss_amount >= 0 AND event_count >= 0)
);

CREATE TABLE quality_case_entities (
  case_entity_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000000) NOT NULL,
  case_id NUMBER NOT NULL,
  entity_id NUMBER NOT NULL,
  role VARCHAR2(40) NOT NULL,
  evidence_score NUMBER NOT NULL,
  CONSTRAINT pk_quality_case_entities PRIMARY KEY (case_entity_id),
  CONSTRAINT fk_quality_case_entities_1 FOREIGN KEY (case_id) REFERENCES quality_cases (case_id),
  CONSTRAINT fk_quality_case_entities_2 FOREIGN KEY (entity_id) REFERENCES trace_entities (entity_id),
  CONSTRAINT ck_quality_case_entities_1 CHECK (evidence_score BETWEEN 0 AND 100)
);

CREATE TABLE work_centers (
  center_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000000) NOT NULL,
  plant_id NUMBER NOT NULL,
  name VARCHAR2(160) NOT NULL,
  CONSTRAINT pk_work_centers PRIMARY KEY (center_id),
  CONSTRAINT fk_work_centers_1 FOREIGN KEY (plant_id) REFERENCES plants (plant_id)
);

CREATE TABLE material_transfers (
  transfer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000000) NOT NULL,
  from_center_id NUMBER NOT NULL,
  to_center_id NUMBER NOT NULL,
  quantity_units NUMBER NOT NULL,
  description VARCHAR2(200) NOT NULL,
  CONSTRAINT pk_material_transfers PRIMARY KEY (transfer_id),
  CONSTRAINT fk_material_transfers_1 FOREIGN KEY (from_center_id) REFERENCES work_centers (center_id),
  CONSTRAINT fk_material_transfers_2 FOREIGN KEY (to_center_id) REFERENCES work_centers (center_id),
  CONSTRAINT ck_material_transfers_1 CHECK (quantity_units > 0 AND quantity_units = TRUNC(quantity_units)),
  CONSTRAINT ck_material_transfers_2 CHECK (from_center_id <> to_center_id)
);

CREATE INDEX ix_components_plant_id ON components (plant_id);

CREATE INDEX ix_production_orders_customer_site_id ON production_orders (customer_site_id);

CREATE INDEX ix_production_orders_plant_id ON production_orders (plant_id);

CREATE INDEX ix_production_order_lines_production_order_id ON production_order_lines (production_order_id);

CREATE INDEX ix_production_order_lines_component_id ON production_order_lines (component_id);

CREATE INDEX ix_quality_observations_customer_site_id ON quality_observations (customer_site_id);

CREATE INDEX ix_observation_components_observation_id ON observation_components (observation_id);

CREATE INDEX ix_observation_components_component_id ON observation_components (component_id);

CREATE INDEX ix_trace_entities_production_order_id ON trace_entities (production_order_id);

CREATE INDEX ix_trace_entities_plant_id ON trace_entities (plant_id);

CREATE INDEX ix_trace_relationships_from_entity ON trace_relationships (from_entity);

CREATE INDEX ix_trace_relationships_to_entity ON trace_relationships (to_entity);

CREATE INDEX ix_quality_case_entities_case_id ON quality_case_entities (case_id);

CREATE INDEX ix_quality_case_entities_entity_id ON quality_case_entities (entity_id);

CREATE INDEX ix_work_centers_plant_id ON work_centers (plant_id);

CREATE INDEX ix_material_transfers_from_center_id ON material_transfers (from_center_id);

CREATE INDEX ix_material_transfers_to_center_id ON material_transfers (to_center_id);


COMMENT ON TABLE plants IS 'Fictional electronics assembly and test plants. Capacity is a daily unit snapshot, not a promise of available machine hours.';
COMMENT ON TABLE components IS 'Plant-specific electronic module revision, board material grade and assembly/test route. Purchased packaged semiconductors are traced as material lots. All costs are USD per unit.';
COMMENT ON TABLE customer_sites IS 'Synthetic electronic-device customer sites and their fulfillment contacts. LOCATION is the delivery point.';
COMMENT ON TABLE production_orders IS 'One production order belongs to one customer site and one plant. Scheduled dates are independent of quantities.';
COMMENT ON TABLE production_order_lines IS 'Component quantities planned at the order plant. LINE_TOTAL is quantity times unit cost.';
COMMENT ON COLUMN production_orders.order_total IS 'Sum of line material costs plus setup cost. This is planned manufacturing cost, not recognized revenue.';
COMMENT ON COLUMN production_order_lines.line_total IS 'Quantity times unit cost. Excludes order setup cost.';
COMMENT ON TABLE quality_observations IS 'Electrical test counts, rejected module percentages, rework and test downtime measured for synthetic module runs.';
COMMENT ON TABLE trace_entities IS 'Production orders, material lots, machines, suppliers, inspections, certificates and plants. Shared use does not prove a defect.';
COMMENT ON TABLE material_transfers IS 'Physical material movements between work centers. Cycles can represent rework.';

