-- SQL twin of 01_seed_stores.mongo.js -- the SAME 5 documents, generated
-- from the same fixture, for attendees whose mongosh connection is blocked.
-- Every invariant the .mongo.js header lists holds here too, including the
-- STRING item_id "1000" planted in s_104 that Lab 3 depends on.
-- Re-run safe: the DELETE makes a second run idempotent.
CREATE JSON COLLECTION TABLE IF NOT EXISTS "stores";
DELETE FROM "stores";

INSERT INTO "stores" (data) VALUES
('{"_id":"s_100","name":"Burger Palace Downtown","menus":[{"menu_id":10,"name":"All Day Menu","start_time":"00:00","end_time":"23:59","active":true,"categories":[{"category_id":100,"name":"Burgers","items":[{"item_id":1000,"name":"Lunch Classic","description":"Char-grilled smash patty, aged cheddar, brioche bun","price":1299,"active":true},{"item_id":1001,"name":"Bacon Double Stack","description":"Two smash patties, thick-cut bacon, smoked gouda","price":1599,"active":true}]},{"category_id":101,"name":"Sides","items":[{"item_id":1002,"name":"French Fries","description":"Twice-fried golden potato fries with sea salt","price":499,"active":true},{"item_id":1003,"name":"Garden Salad","description":"Crisp greens, heirloom tomato, house vinaigrette","price":899,"active":true}]}]}]}');
INSERT INTO "stores" (data) VALUES
('{"_id":"s_101","name":"Burger Palace Uptown","menus":[{"menu_id":11,"name":"All Day Menu","start_time":"00:00","end_time":"23:59","active":true,"categories":[{"category_id":110,"name":"Burgers","items":[{"item_id":1000,"name":"Classic Cheeseburger","description":"Char-grilled smash patty, aged cheddar, brioche bun","price":1299,"active":true},{"item_id":1001,"name":"Bacon Double Stack","description":"Two smash patties, thick-cut bacon, smoked gouda","price":1599,"active":true},{"item_id":1004,"name":"Black Bean Chipotle Burger","description":"Smoky black bean patty, fiery chipotle aioli, no meat","price":1199,"active":true}]},{"category_id":111,"name":"Sides","items":[{"item_id":1002,"name":"French Fries","description":"Twice-fried golden potato fries with sea salt","price":499,"active":true},{"item_id":1003,"name":"Garden Salad","description":"Crisp greens, heirloom tomato, house vinaigrette","price":899,"active":true}]}]}]}');
INSERT INTO "stores" (data) VALUES
('{"_id":"s_102","name":"Burger Palace Riverside","menus":[{"menu_id":12,"name":"All Day Menu","start_time":"00:00","end_time":"23:59","active":true,"categories":[{"category_id":120,"name":"Burgers","items":[{"item_id":1000,"name":"Classic Cheeseburger","description":"Char-grilled smash patty, aged cheddar, brioche bun","price":1299,"active":true},{"item_id":1005,"name":"Buffalo Chicken Sandwich","description":"Crispy chicken thigh, cayenne hot sauce, blue cheese","price":1349,"active":true}]},{"category_id":121,"name":"Sides","items":[{"item_id":1002,"name":"French Fries","description":"Twice-fried golden potato fries with sea salt","price":499,"active":true},{"item_id":1006,"name":"Chocolate Malt Shake","description":"Hand-spun chocolate malt, whole milk, whipped cream","price":599,"active":true}]}]}]}');
INSERT INTO "stores" (data) VALUES
('{"_id":"s_103","name":"Burger Palace Campus","menus":[{"menu_id":13,"name":"All Day Menu","start_time":"00:00","end_time":"23:59","active":true,"categories":[{"category_id":130,"name":"Burgers","items":[{"item_id":1000,"name":"Classic Cheeseburger","description":"Char-grilled smash patty, aged cheddar, brioche bun","price":1299,"active":true},{"item_id":1004,"name":"Black Bean Chipotle Burger","description":"Smoky black bean patty, fiery chipotle aioli, no meat","price":1199,"active":true},{"item_id":1005,"name":"Buffalo Chicken Sandwich","description":"Crispy chicken thigh, cayenne hot sauce, blue cheese","price":1349,"active":true}]},{"category_id":131,"name":"Sides","items":[{"item_id":1002,"name":"French Fries","description":"Twice-fried golden potato fries with sea salt","price":499,"active":true},{"item_id":1003,"name":"Garden Salad","description":"Crisp greens, heirloom tomato, house vinaigrette","price":899,"active":true},{"item_id":1006,"name":"Chocolate Malt Shake","description":"Hand-spun chocolate malt, whole milk, whipped cream","price":599,"active":true}]}]}]}');
INSERT INTO "stores" (data) VALUES
('{"_id":"s_104","name":"Burger Palace Airport","menus":[{"menu_id":14,"name":"All Day Menu","start_time":"00:00","end_time":"23:59","active":true,"categories":[{"category_id":140,"name":"Burgers","items":[{"item_id":"1000","name":"Classic Cheeseburger","description":"Char-grilled smash patty, aged cheddar, brioche bun","price":1499,"active":true},{"item_id":"1005","name":"Buffalo Chicken Sandwich","description":"Crispy chicken thigh, cayenne hot sauce, blue cheese","price":1499,"active":true}]},{"category_id":141,"name":"Sides","items":[{"item_id":"1002","name":"French Fries","description":"Twice-fried golden potato fries with sea salt","price":649,"active":true}]}]}]}');
COMMIT;

-- STATE CHECK: expect 5
SELECT COUNT(*) AS stores_seeded FROM "stores";
