-- Lab 8 FALLBACK: used only if MENU_MODEL is unavailable. Covers the WHOLE
-- module: precomputed vector literals for every item AND every query probe -
-- 'spicy vegetarian noodles', 'vegan-friendly noodles', 'kid-friendly comfort food'
-- - plus alternate search/freshness/capstone statements that use them.
-- BUILD PHASE: the VECTOR literals below are generated by running
-- VECTOR_EMBEDDING on a model-enabled instance and pasting the results;
-- placeholders here are structural. Honest note for the guide: with the
-- fallback, same-commit freshness still holds (the literal commits with the
-- row); the "no embedding service" beat degrades.

ALTER TABLE item ADD (desc_vec VECTOR(384, FLOAT32));

CREATE TABLE IF NOT EXISTS query_vec (
  probe VARCHAR2(50) PRIMARY KEY,
  v     VECTOR(384, FLOAT32)
);
DELETE FROM query_vec;
-- INSERT INTO query_vec VALUES ('spicy vegetarian noodles',  TO_VECTOR('[...384 floats...]'));
-- INSERT INTO query_vec VALUES ('vegan-friendly noodles',    TO_VECTOR('[...384 floats...]'));
-- INSERT INTO query_vec VALUES ('kid-friendly comfort food', TO_VECTOR('[...384 floats...]'));
-- UPDATE item SET desc_vec = TO_VECTOR('[...]') WHERE item_id = 1000;  -- one per item

-- Alternate semantic search (same shape as the model version):
SELECT i.item_name, i.price
FROM   item i, query_vec q
WHERE  i.active AND q.probe = 'spicy vegetarian noodles'
ORDER  BY VECTOR_DISTANCE(i.desc_vec, q.v, COSINE)
FETCH FIRST 5 ROWS ONLY;
