-- Full reset: drop everything the workshop creates, in dependency order.
DROP VIEW  IF EXISTS pos_menu_v;
DROP VIEW  IF EXISTS "store_menu_dv";
DROP PROPERTY GRAPH IF EXISTS order_graph;
DROP TABLE IF EXISTS order_item         CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS ord                CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS customer           CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS item_option        CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS extra              CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS item_special_hours CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS menu_item          CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS category           CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS menu               CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS item               CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS store              CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS "orders"           CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS "stores"           CASCADE CONSTRAINTS;

-- STATE CHECK: expect 0
SELECT COUNT(*) AS remaining FROM user_tables
WHERE table_name IN ('STORE','MENU','CATEGORY','ITEM','MENU_ITEM','EXTRA',
                     'ITEM_OPTION','ITEM_SPECIAL_HOURS','ORD','ORDER_ITEM','CUSTOMER');
