/*
 * 10_returns.sql
 * Retail LiveStack return-data schema extension.
 * Adds a return authorization workload on top of the mature social-commerce baseline.
 */

SET SERVEROUTPUT ON

PROMPT =====================================================
PROMPT Creating Retail LiveStack return-data objects
PROMPT =====================================================

DECLARE
  PROCEDURE run_ddl(p_sql CLOB, p_ignore_code NUMBER DEFAULT -955) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != p_ignore_code THEN
        RAISE;
      END IF;
  END;
BEGIN
  run_ddl(q'[
    CREATE TABLE return_policy_clauses (
      policy_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      clause_code     VARCHAR2(60) NOT NULL UNIQUE,
      clause_title    VARCHAR2(200) NOT NULL,
      category        VARCHAR2(80),
      clause_text     CLOB NOT NULL,
      severity        VARCHAR2(30) DEFAULT 'standard'
                      CHECK (severity IN ('standard','manager_review','deny','vip_override')),
      effective_start DATE DEFAULT DATE '2026-01-01',
      effective_end   DATE,
      created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
    )
  ]');

  run_ddl(q'[
    CREATE TABLE return_requests (
      return_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      order_id           NUMBER NOT NULL REFERENCES orders(order_id),
      customer_id        NUMBER NOT NULL REFERENCES customers(customer_id),
      product_id         NUMBER NOT NULL REFERENCES products(product_id),
      return_reason      VARCHAR2(120) NOT NULL,
      damage_description CLOB,
      return_channel     VARCHAR2(40) DEFAULT 'web'
                         CHECK (return_channel IN ('web','store','contact_center','marketplace','mobile')),
      return_value       NUMBER(12,2) DEFAULT 0,
      risk_rating        VARCHAR2(20) DEFAULT 'Medium'
                         CHECK (risk_rating IN ('Low','Medium','High','Very High')),
      recommendation     VARCHAR2(30) DEFAULT 'Review'
                         CHECK (recommendation IN ('Approve','Deny','Request Info','Review')),
      status             VARCHAR2(40) DEFAULT 'Needs Review'
                         CHECK (status IN ('Needs Review','In Review','Approved Draft','Denied Draft','Needs Info Draft','Closed')),
      policy_clause      VARCHAR2(60),
      confidence_score   NUMBER(4,2) DEFAULT 0,
      requested_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
      created_at         TIMESTAMP DEFAULT SYSTIMESTAMP,
      updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP
    ) INMEMORY MEMCOMPRESS FOR QUERY HIGH
  ]');

  run_ddl(q'[
    CREATE TABLE return_documents (
      document_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      return_id        NUMBER NOT NULL REFERENCES return_requests(return_id) ON DELETE CASCADE,
      document_type    VARCHAR2(60) NOT NULL,
      title            VARCHAR2(220) NOT NULL,
      excerpt          CLOB,
      similarity_score NUMBER(5,4),
      source_uri       VARCHAR2(500),
      created_at       TIMESTAMP DEFAULT SYSTIMESTAMP
    )
  ]');

  run_ddl(q'[
    CREATE TABLE return_events (
      event_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      return_id    NUMBER NOT NULL REFERENCES return_requests(return_id) ON DELETE CASCADE,
      event_type   VARCHAR2(80) NOT NULL,
      event_note   CLOB,
      actor        VARCHAR2(120),
      created_at   TIMESTAMP DEFAULT SYSTIMESTAMP
    )
  ]');

  run_ddl(q'[
    CREATE TABLE return_decisions (
      decision_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      return_id        NUMBER NOT NULL REFERENCES return_requests(return_id) ON DELETE CASCADE,
      decision_type    VARCHAR2(40) NOT NULL,
      decision_summary CLOB,
      confidence_score NUMBER(4,2),
      created_by       VARCHAR2(120) DEFAULT 'returns_ai_agent',
      created_at       TIMESTAMP DEFAULT SYSTIMESTAMP
    )
  ]');

  run_ddl('CREATE INDEX idx_return_requests_status ON return_requests(status, risk_rating)');
  run_ddl('CREATE INDEX idx_return_requests_customer ON return_requests(customer_id, requested_at)');
  run_ddl('CREATE INDEX idx_return_requests_order ON return_requests(order_id)');
  run_ddl('CREATE INDEX idx_return_documents_return ON return_documents(return_id, similarity_score)');
  run_ddl('CREATE INDEX idx_return_events_return ON return_events(return_id, created_at)');
  run_ddl('CREATE INDEX idx_return_decisions_return ON return_decisions(return_id, created_at)');
END;
/

CREATE OR REPLACE VIEW retail_return_workbench_v AS
SELECT
  rr.return_id,
  rr.order_id,
  rr.customer_id,
  c.first_name || ' ' || c.last_name AS customer_name,
  c.customer_tier,
  c.lifetime_value,
  rr.product_id,
  p.product_name,
  p.category,
  rr.return_reason,
  rr.return_value,
  rr.risk_rating,
  rr.recommendation,
  rr.status,
  rr.policy_clause,
  rr.confidence_score,
  rr.requested_at,
  COUNT(rd.document_id) AS evidence_count
FROM return_requests rr
JOIN customers c ON c.customer_id = rr.customer_id
JOIN products p ON p.product_id = rr.product_id
LEFT JOIN return_documents rd ON rd.return_id = rr.return_id
GROUP BY
  rr.return_id, rr.order_id, rr.customer_id, c.first_name, c.last_name,
  c.customer_tier, c.lifetime_value, rr.product_id, p.product_name, p.category,
  rr.return_reason, rr.return_value, rr.risk_rating, rr.recommendation, rr.status,
  rr.policy_clause, rr.confidence_score, rr.requested_at;

COMMENT ON TABLE return_requests IS 'Retail return authorization cases scored by policy, customer history, and product evidence.';
COMMENT ON TABLE return_documents IS 'RAG grounding evidence for return decisions: policy clauses, image notes, warranty terms, and customer history snippets.';
COMMENT ON TABLE retail_return_workbench_v IS 'Return queue view used by retail analytics and Ask Retail Data examples.';

COMMIT;

PROMPT Retail returns schema ready.
