#!/bin/bash
#
sqlplus /nolog << STOP
@imlogin.sql
set echo on
set serveroutput on;

declare
  v_ddl varchar2(1000);
begin
  for tab_cursor in (
    select owner, table_name
    from   dba_tables
    where  owner not in ('AUDSYS','SYS')
    and    inmemory = 'ENABLED'
  )
  loop
    v_ddl := 'alter table '||tab_cursor.owner||'.'||tab_cursor.table_name||' no inmemory';
    dbms_output.put_line(v_ddl);
    execute immediate v_ddl;
  end loop;
  --
  for part_cursor in (
    select table_owner, table_name, partition_name
    from   dba_tab_partitions
    where  table_owner not in ('AUDSYS','SYS')
    and    inmemory = 'ENABLED'
  )
  loop
    v_ddl := 'alter table '||part_cursor.table_owner||'.'||part_cursor.table_name||
      ' modify partition '||part_cursor.partition_name||' no inmemory';
    dbms_output.put_line(v_ddl);
    execute immediate v_ddl;
  end loop;
end;
/
alter table lineorder drop column v1; 
DROP INMEMORY JOIN GROUP lineorder_jg1;
DROP INMEMORY JOIN GROUP lineorder_jg2;
DROP INMEMORY JOIN GROUP lineorder_jg3;
alter system set inmemory_optimized_arithmetic = 'DISABLE';
exit;
STOP
#
exit
