SET SERVEROUTPUT ON
PROMPT Retail workshop readiness check
SELECT check_name, status, detail
FROM (
  SELECT 'base tables' AS check_name,
         CASE WHEN COUNT(*) >= 29 THEN 'OK' ELSE 'CHECK' END AS status,
         TO_CHAR(COUNT(*)) AS detail
  FROM user_tables
  WHERE table_name IN ('BRANDS','PRODUCTS','PRODUCT_ATTRIBUTES','FULFILLMENT_CENTERS','INVENTORY','CUSTOMERS','ORDERS','ORDER_ITEMS','SHIPMENTS','INFLUENCERS','SOCIAL_POSTS','POST_PRODUCT_MENTIONS','INFLUENCER_CONNECTIONS','BRAND_INFLUENCER_LINKS','DEMAND_FORECASTS','AGENT_ACTIONS','APP_USERS','APP_DATASET_STATE','EVENT_STREAM','PRODUCT_EMBEDDINGS','POST_EMBEDDINGS','SEMANTIC_MATCHES','FULFILLMENT_ZONES','DEMAND_REGIONS','RETURN_POLICY_CLAUSES','RETURN_REQUESTS','RETURN_DOCUMENTS','RETURN_EVENTS','RETURN_DECISIONS')
  UNION ALL
  SELECT 'json duality views', CASE WHEN COUNT(*) >= 2 THEN 'OK' ELSE 'CHECK' END, TO_CHAR(COUNT(*))
  FROM user_views WHERE view_name IN ('ORDERS_DV','PRODUCTS_INVENTORY_DV')
  UNION ALL
  SELECT 'retail semantic views', CASE WHEN COUNT(*) >= 5 THEN 'OK' ELSE 'CHECK' END, TO_CHAR(COUNT(*))
  FROM user_views WHERE view_name IN ('RETAIL_RETURNS_WORKFLOW_V','RETAIL_SIGNAL_PRODUCT_V','RETAIL_ORDER_RETURN_V','RETAIL_FULFILLMENT_RISK_V','RETAIL_RETURN_WORKBENCH_V')
  UNION ALL
  SELECT 'MiniLM model', CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'CHECK' END, TO_CHAR(COUNT(*))
  FROM user_mining_models WHERE model_name = 'ALL_MINILM_L12_V2'
  UNION ALL
  SELECT 'property graph', CASE WHEN COUNT(*) = 1 THEN 'OK' ELSE 'CHECK' END, TO_CHAR(COUNT(*))
  FROM user_property_graphs WHERE graph_name = 'INFLUENCER_NETWORK'
  UNION ALL
  SELECT 'OML models', CASE WHEN COUNT(*) = 4 THEN 'OK' ELSE 'CHECK' END, TO_CHAR(COUNT(*))
  FROM user_mining_models WHERE model_name IN ('DEMAND_SURGE_MODEL','CUSTOMER_SEGMENT_MODEL','REVENUE_PREDICT_MODEL','PRODUCT_CLUSTER_MODEL')
  UNION ALL
  SELECT 'agent tools', CASE WHEN COUNT(*) >= 5 THEN 'OK' ELSE 'CHECK' END, TO_CHAR(COUNT(*))
  FROM user_objects WHERE object_type = 'FUNCTION' AND object_name IN ('DETECT_TRENDING_PRODUCTS','CHECK_PRODUCT_INVENTORY','FIND_BEST_FULFILLMENT','GET_INFLUENCER_NETWORK','LOG_AGENT_DECISION')
  UNION ALL
  SELECT 'VPD policy functions', CASE WHEN COUNT(*) = 2 THEN 'OK' ELSE 'CHECK' END, TO_CHAR(COUNT(*))
  FROM user_objects WHERE object_type = 'FUNCTION' AND object_name IN ('VPD_FULFILLMENT_REGION','VPD_ORDERS_REGION')
  UNION ALL
  SELECT 'VPD policies', CASE WHEN COUNT(*) = 2 THEN 'OK' ELSE 'CHECK' END, TO_CHAR(COUNT(*))
  FROM all_policies
  WHERE object_owner = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
    AND policy_name IN ('VPD_FC_REGION','VPD_ORDERS_REGION')
)
ORDER BY check_name;
