#!/usr/bin/env python3
"""Static and local relational validation; does not claim Oracle execution."""
from pathlib import Path
import re,json,sqlite3,ast,hashlib,xml.etree.ElementTree as ET
from urllib.parse import unquote,urlsplit
R=Path(__file__).resolve().parents[1]
L=R/'stack/load_data/manufacturing-platform-handoff-loader.sql';sql=L.read_text();errors=[];checks={}
def check(name,condition,detail=None):
 checks[name]={'pass':bool(condition),'detail':detail}
 if not condition:errors.append(name)
def split_values(text):
 values=[];start=0;depth=0;quote=False;i=0
 while i<len(text):
  c=text[i]
  if c=="'":
   if quote and i+1<len(text) and text[i+1]=="'":i+=2;continue
   quote=not quote
  elif not quote:
   if c=='(':depth+=1
   elif c==')':depth-=1
   elif c==',' and depth==0:values.append(text[start:i].strip());start=i+1
  i+=1
 values.append(text[start:].strip());return values

def val(s):
 if s=='NULL':return None
 if s.startswith("'"):return s[1:-1].replace("''","'")
 try:return float(s) if '.' in s else int(s)
 except ValueError:return s
D={}
for line in sql.splitlines():
 m=re.match(r'INSERT INTO (\w+) \(([^)]+)\) VALUES \((.*)\);$',line)
 if m:
  tab,cols,vs=m.groups();keys=cols.split(', ');vv=split_values(vs)
  check('insert_arity_'+tab, len(keys)==len(vv))
  D.setdefault(tab,[]).append(dict(zip(keys,map(val,vv))))
fixture=json.loads((R/'validation/fixture-data.json').read_text())
check('loader_fixture_exact_alignment',D==fixture,{k:len(v) for k,v in D.items()})
# Run table constraints and relational views in SQLite as a separate fixture check.
# Oracle objects, embeddings, SQL/PGQ, Spatial, OML and AI are NOT executed here.
con=sqlite3.connect(':memory:');con.execute('PRAGMA foreign_keys=ON')
con.create_function('TRUNC',1,lambda x:x if isinstance(x,str) else int(x))
contract={};fks=[]
for m in re.finditer(r'CREATE TABLE (\w+) \((.*?)\n\);',sql,re.S):
 name,body=m.groups();cols={}
 for line in body.splitlines():
  cm=re.match(r'\s*(\w+)\s+(NUMBER|VARCHAR2|DATE|TIMESTAMP|JSON|MDSYS\.SDO_GEOMETRY|VECTOR|GENERATED)(.*)',line)
  if cm:cols[cm.group(1)]=(cm.group(2)+cm.group(3)).rstrip(',')
 for fk in re.finditer(r'FOREIGN KEY \(([^)]+)\) REFERENCES (\w+) \(([^)]+)\)',body):fks.append({'table':name,'columns':fk[1].split(', '),'parent':fk[2],'parent_columns':fk[3].split(', ')})
 contract[name]={'type':'table','columns':cols,'seed_rows':len(D.get(name,[]))}
 stmt=m.group();stmt=re.sub(r'GENERATED BY DEFAULT ON NULL AS IDENTITY \(START WITH \d+\)','',stmt)
 stmt=stmt.replace('MDSYS.SDO_GEOMETRY','TEXT').replace('VECTOR(384)','TEXT')
 stmt=re.sub(r"DEFAULT TIMESTAMP '[^']+'",'',stmt).replace('DEFAULT SYSTIMESTAMP','')
 try:con.execute(stmt)
 except Exception as e:errors.append('sqlite_ddl:'+name+':'+str(e))
for name,rows in D.items():
 for row in rows:
  values=[]
  for v in row.values():
   if isinstance(v,str) and (v.startswith("DATE '") or v.startswith("TIMESTAMP '")):v=v.split("'",2)[1]
   elif isinstance(v,str) and v.startswith("JSON('"):v=v[6:-2]
   values.append(v)
  try:con.execute('INSERT INTO '+name+' ('+','.join(row)+') VALUES ('+','.join('?' for _ in row)+')',values)
  except Exception as e:errors.append('sqlite_insert:'+name+':'+str(e));break
check('foreign_key_integrity',not list(con.execute('PRAGMA foreign_key_check')),len(fks))
for m in re.finditer(r'CREATE OR REPLACE VIEW (\w+) AS\n(.*?);',sql,re.S):
 name,body=m.groups();statement='CREATE VIEW '+name+' AS '+body
 statement=re.sub(r"\b(?:DATE|TIMESTAMP) ('[^']+')",r'\1',statement);statement=re.sub(r'\bNVL\(', 'IFNULL(',statement)
 try:
  con.execute(statement);count=con.execute('SELECT COUNT(*) FROM '+name).fetchone()[0]
  contract[name]={'type':'view','columns':{d[0]:'derived' for d in con.execute('SELECT * FROM '+name+' LIMIT 0').description},'rows':count}
 except Exception as e:errors.append('sqlite_view:'+name+':'+str(e))
queries={
 'order_totals':'''SELECT COUNT(*) FROM production_orders o LEFT JOIN (SELECT production_order_id,SUM(line_total) v FROM production_order_lines GROUP BY production_order_id) l USING(production_order_id) WHERE v IS NULL OR v+setup_cost<>order_total''',
 'component_plant_alignment':'''SELECT COUNT(*) FROM production_order_lines l JOIN production_orders o USING(production_order_id) JOIN components c USING(component_id) WHERE o.plant_id<>c.plant_id''',
 'inspection_percentages':'''SELECT COUNT(*) FROM quality_observations WHERE ABS(defect_rate_pct-100.0*rejected_units/inspected_units)>0.00001''',
 'exercise_order_id_unused':'SELECT COUNT(*) FROM production_orders WHERE production_order_id=900001',
 'exercise_line_id_unused':'SELECT COUNT(*) FROM production_order_lines WHERE order_line_id=990001',
}
for name,q in queries.items():
 try:check(name,con.execute(q).fetchone()[0]==0)
 except Exception as e:errors.append(name+':'+str(e))
labels=dict(con.execute('SELECT review_label,COUNT(*) FROM oml_quality_training_v GROUP BY review_label'))
check('oml_classes',labels=={'REVIEW':96,'STABLE':96},labels)
check('independent_quantity_and_schedule',con.execute('SELECT COUNT(*) FROM production_order_lines WHERE quantity>20').fetchone()[0]>0)
# Concrete non-Oracle graph checks from the same relational rows.
shared=list(con.execute('''SELECT a.entity_key,b.entity_key,s.entity_key FROM trace_entities a JOIN trace_relationships e1 ON e1.from_entity=a.entity_id JOIN trace_entities s ON s.entity_id=e1.to_entity JOIN trace_relationships e2 ON e2.to_entity=s.entity_id JOIN trace_entities b ON b.entity_id=e2.from_entity WHERE a.entity_type='production_order' AND b.entity_type='production_order' AND a.entity_id<b.entity_id AND s.entity_type IN ('material_lot','supplier','inspection','certificate') AND (a.risk_score>=70 OR b.risk_score>=70)'''))
check('shared_lot_pairs',len(shared)==3,shared)
check('optional_pgx_seed_ids',all(any(r['center_id']==i for r in D['work_centers']) for i in [534,597,934,387,406]))
check('reserved_component',con.execute('SELECT COUNT(*) FROM components WHERE component_id=1 AND plant_id=1 AND unit_cost=125').fetchone()[0]==1)
# Main graph definition and duality shape must agree between loader and lesson.
def normalize(s):return re.sub(r'\s+',' ',s).strip().lower()
graph=re.search(r'CREATE PROPERTY GRAPH production_quality_network[\s\S]*?\n  \);',sql)
lab=(R/'production-quality-network/production-quality-network.md').read_text();g2=re.search(r'CREATE PROPERTY GRAPH production_quality_network[\s\S]*?\n  \);',lab)
check('graph_ddl_lab_loader_exact',graph is not None and g2 is not None and normalize(graph.group())==normalize(g2.group()))
dv=re.search(r'CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW production_orders_dv[\s\S]*?FROM production_orders r WITH UPDATE;',sql)
dvlab=(R/'production-order-duality/production-order-duality.md').read_text();dv2=re.search(r'CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW production_orders_dv[\s\S]*?FROM production_orders r WITH INSERT UPDATE;',dvlab)
check('duality_ddl_lab_loader_alignment',dv is not None and dv2 is not None and normalize(dv.group())==normalize(dv2.group().replace('WITH INSERT UPDATE','WITH UPDATE')))
contract['production_orders_dv']={'type':'duality_view','columns':{'data':'JSON'},'json_keys':re.findall(r"'([^']+)'\s*:",dv.group()) if dv else []}
# Parse every notebook and its embedded visualization configuration and Python paragraphs.
nbcounts={};pycount=0
for p in R.rglob('*.dsnb'):
 d=json.loads(p.read_text());nbcounts[str(p.relative_to(R))]=len(d[0]['paragraphs'])
 for n in d:
  if n.get('templateConfig'):json.loads(n['templateConfig'])
  for par in n['paragraphs']:
   check('notebook_no_cached_results',par.get('result') is None)
   if par.get('visualizationConfig'):json.loads(par['visualizationConfig'])
   lines=par['message']
   if lines and lines[0].strip()=='%python-pgx':ast.parse('\n'.join(lines[1:]));pycount+=1
check('notebook_structure',sorted(nbcounts.values())==[8,43],{'paragraphs':nbcounts,'python_paragraphs':pycount})
# Manifests, local paths, image references, internal lesson navigation, fences and copy wrappers.
manifest_paths=list(R.glob('workshops/*/manifest.json'));manifest_data=[json.loads(p.read_text()) for p in manifest_paths]
check('manifests_synchronized',manifest_data[0]==manifest_data[1])
lessons=[]
for p,d in zip(manifest_paths,manifest_data):
 for row in d['tutorials']:
  if row['filename'].startswith('http'):continue
  dest=(p.parent/row['filename']).resolve();check('manifest_'+dest.parent.name,dest.is_file());
  if dest not in lessons:lessons.append(dest)
labids={p.parent.name for p in lessons};image_refs=[];links=[];blockcounts={};taskcounts={};known=set(contract)|{'thomas_app_data','thomas_production_order_docs','otto_quality_review_settings','otto_quality_review_scoring_data','production_quality_network'}
platform={'all_mining_models','user_mining_models','user_cloud_ai_profiles','user_cloud_ai_profile_attributes','user_json_duality_views','user_ai_agents','user_ai_agent_tools','user_ai_agent_team_history','user_ai_agent_tool_history','dual'}
unknown=[]
for p in R.rglob('*.md'):
 t=p.read_text();check('fences_'+str(p.relative_to(R)),len(re.findall(r'^\s*```',t,re.M))%2==0)
 check('copy_'+str(p.relative_to(R)),t.count('<copy>')==t.count('</copy>'))
 for im,url in re.findall(r'(!?)\[[^\]]*\]\(([^)]+)\)',t):
  url=url.split(' "')[0].strip();parsed=urlsplit(url)
  if parsed.scheme in ('http','https','mailto'):links.append(url);continue
  if url.startswith('?lab='):
   check('nav_'+url,url.split('=',1)[1].split('#')[0] in labids);continue
  if not parsed.path:continue
  dest=(p.parent/unquote(parsed.path)).resolve();check('link_'+str(p.relative_to(R))+':'+url,dest.is_file())
  if im:image_refs.append(str(dest.relative_to(R)))
 if p in lessons:
  taskcounts[p.parent.name]=len(re.findall(r'^## Task \d+:',t,re.M));blocks=re.findall(r'```sql\s*([\s\S]*?)```',t);blockcounts[p.parent.name]=len(blocks)
  for b in blocks:
   ctes=set(re.findall(r'\b(\w+)\s+AS\s*\(',b,re.I))
   for obj in re.findall(r'\b(?:FROM|JOIN)\s+(\w+)',re.sub(r'--[^\n]*','',b),re.I):
    if obj.lower() not in known|platform|{c.lower() for c in ctes}|{'graph_table','json_table','table'}:unknown.append((p.parent.name,obj))
check('schema_references',not unknown,unknown)
check('lesson_count',len(lessons)==11)
for p in R.rglob('*.svg'):ET.parse(p)
for p in R.rglob('*.json'):json.loads(p.read_text())
quiz=(R/'final-quiz/final-quiz.md').read_text();check('quiz',quiz.count('Q:')==7 and len(re.findall(r'^\s*\* ',re.search(r'```quiz score([\s\S]*?)```',quiz).group(1),re.M))==7 and 'passing: 75' in quiz)
check('loader_entrypoint', '@load_data/manufacturing-platform-handoff-loader.sql ${local.new_password} ATP${var.resId}_high' in (R/'stack/adb.tf').read_text())
# Columns of aliases bound to base tables or known views must exist.
missingcols=[]
for p in lessons:
 for b in re.findall(r'```sql\s*([\s\S]*?)```',p.read_text()):
  aliases={a.lower():tab.lower() for tab,a in re.findall(r'\b(?:FROM|JOIN)\s+(\w+)\s+(\w+)',b,re.I) if tab.lower() in contract}
  for alias,col in re.findall(r'\b(\w+)\.(\w+)\b',re.sub(r"'[^']*'",'',re.sub(r'--[^\n]*','',b))):
   if alias.lower() in aliases:
    cols=contract[aliases[alias.lower()]]['columns'];allowed=set(cols)|({'component_embedding'} if aliases[alias.lower()]=='components' else set())
    if col.lower() not in allowed:missingcols.append((p.parent.name,alias,col,aliases[alias.lower()]))
check('base_table_and_view_columns',not missingcols,missingcols)
coverage=json.loads((R/'validation/screenshot-coverage.json').read_text())
result={'date':'2026-09-22','scope':'Static structure plus SQLite fixture constraints and relational calculations. Not Oracle execution.','passed':not errors,'errors':errors,'checks':checks,'table_counts':{k:len(v) for k,v in D.items()},'foreign_keys':len(fks),'task_counts':taskcounts,'sql_blocks':blockcounts,'image_references':len(image_refs),'unique_images_referenced':len(set(image_refs)),'external_links':sorted(set(links)),'authentic_manufacturing_screenshots':coverage['authentic_manufacturing_captures'],'pending_capture_positions':len(coverage['pending']),'manual_oracle_validation':'see live-validation.json (separate from these static checks)','green_button_validation':'not_run'}
(R/'validation/static-results.json').write_text(json.dumps(result,indent=2))
(R/'validation/schema-contract.json').write_text(json.dumps({'objects':contract,'foreign_keys':fks},indent=2))
print(json.dumps({k:v for k,v in result.items() if k not in ['checks','external_links']},indent=2))
raise SystemExit(0 if not errors else 1)
