/*
 * 10_fraud_graph.sql
 * Dedicated fraud entity property graph for finance-network investigation demos.
 */

SET SERVEROUTPUT ON
PROMPT Creating fraud graph schema...

BEGIN
    EXECUTE IMMEDIATE 'DROP PROPERTY GRAPH fraud_network';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-942, -4043) THEN
            DBMS_OUTPUT.PUT_LINE('Skipping fraud_network drop: ' || SQLERRM);
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE fraud_case_entities CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE fraud_relationships CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE fraud_cases CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE fraud_entities CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE fraud_entities (
    entity_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    entity_key         VARCHAR2(64) NOT NULL UNIQUE,
    display_name       VARCHAR2(160) NOT NULL,
    entity_type        VARCHAR2(30) NOT NULL
                       CHECK (entity_type IN (
                         'account','device','ip_address','payee','merchant',
                         'card','phone','email','branch','case_anchor'
                       )),
    risk_score         NUMBER(5,2) DEFAULT 0 NOT NULL,
    risk_level         VARCHAR2(16) DEFAULT 'medium' NOT NULL
                       CHECK (risk_level IN ('critical','high','medium','low')),
    region             VARCHAR2(80),
    city               VARCHAR2(80),
    channel            VARCHAR2(32) DEFAULT 'unknown' NOT NULL
                       CHECK (channel IN (
                         'mobile','web','branch','atm','contact_center',
                         'payments','merchant','network','unknown'
                       )),
    total_amount       NUMBER(14,2) DEFAULT 0 NOT NULL,
    event_count        NUMBER(8) DEFAULT 0 NOT NULL,
    first_seen         TIMESTAMP DEFAULT SYSTIMESTAMP,
    last_seen          TIMESTAMP DEFAULT SYSTIMESTAMP,
    is_confirmed_fraud NUMBER(1) DEFAULT 0 NOT NULL
                       CHECK (is_confirmed_fraud IN (0, 1))
);

CREATE INDEX idx_fraud_entities_type ON fraud_entities(entity_type);
CREATE INDEX idx_fraud_entities_risk ON fraud_entities(risk_score DESC);
CREATE INDEX idx_fraud_entities_channel ON fraud_entities(channel);

CREATE TABLE fraud_relationships (
    relationship_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    from_entity       NUMBER NOT NULL REFERENCES fraud_entities(entity_id),
    to_entity         NUMBER NOT NULL REFERENCES fraud_entities(entity_id),
    relationship_type VARCHAR2(40) NOT NULL
                      CHECK (relationship_type IN (
                        'shared_device','shared_ip','transfers_to','uses_payee',
                        'card_testing_at','login_from','opened_with','same_phone',
                        'same_email','cashout_at','merchant_velocity','branch_origin'
                      )),
    strength          NUMBER(4,3) DEFAULT 0.5 NOT NULL,
    event_count       NUMBER(8) DEFAULT 1 NOT NULL,
    total_amount      NUMBER(14,2) DEFAULT 0 NOT NULL,
    first_seen        TIMESTAMP DEFAULT SYSTIMESTAMP,
    last_seen         TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_fraud_relationship UNIQUE (from_entity, to_entity, relationship_type)
);

CREATE INDEX idx_fraud_rel_from ON fraud_relationships(from_entity);
CREATE INDEX idx_fraud_rel_to ON fraud_relationships(to_entity);
CREATE INDEX idx_fraud_rel_type ON fraud_relationships(relationship_type);

CREATE TABLE fraud_cases (
    case_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    case_ref     VARCHAR2(64) NOT NULL UNIQUE,
    case_type    VARCHAR2(60) NOT NULL,
    status       VARCHAR2(30) DEFAULT 'investigating' NOT NULL
                 CHECK (status IN ('investigating','confirmed','escalated','monitoring','closed')),
    risk_score   NUMBER(5,2) DEFAULT 0 NOT NULL,
    loss_amount  NUMBER(14,2) DEFAULT 0 NOT NULL,
    event_count  NUMBER(8) DEFAULT 0 NOT NULL,
    opened_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE fraud_case_entities (
    case_entity_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    case_id        NUMBER NOT NULL REFERENCES fraud_cases(case_id),
    entity_id      NUMBER NOT NULL REFERENCES fraud_entities(entity_id),
    role           VARCHAR2(40) NOT NULL
                   CHECK (role IN ('seed','suspect','shared_infrastructure','cashout','victim','merchant','watchlist')),
    evidence_score NUMBER(5,2) DEFAULT 0 NOT NULL,
    CONSTRAINT uq_fraud_case_entity UNIQUE (case_id, entity_id, role)
);

CREATE INDEX idx_fraud_case_entities_case ON fraud_case_entities(case_id);
CREATE INDEX idx_fraud_case_entities_entity ON fraud_case_entities(entity_id);

CREATE PROPERTY GRAPH fraud_network
    VERTEX TABLES (
        fraud_entities KEY (entity_id)
            LABEL entity
            PROPERTIES (
                entity_id,
                entity_key,
                display_name,
                entity_type,
                risk_score,
                risk_level,
                region,
                city,
                channel,
                total_amount,
                event_count,
                is_confirmed_fraud
            ),
        fraud_cases KEY (case_id)
            LABEL fraud_case
            PROPERTIES (
                case_id,
                case_ref,
                case_type,
                status,
                risk_score,
                loss_amount,
                event_count
            )
    )
    EDGE TABLES (
        fraud_relationships
            KEY (relationship_id)
            SOURCE KEY (from_entity) REFERENCES fraud_entities (entity_id)
            DESTINATION KEY (to_entity) REFERENCES fraud_entities (entity_id)
            LABEL related_to
            PROPERTIES (
                relationship_type,
                strength,
                event_count,
                total_amount
            ),
        fraud_case_entities
            KEY (case_entity_id)
            SOURCE KEY (case_id) REFERENCES fraud_cases (case_id)
            DESTINATION KEY (entity_id) REFERENCES fraud_entities (entity_id)
            LABEL contains_entity
            PROPERTIES (
                role,
                evidence_score
            )
    );

COMMIT;

SELECT 'Fraud property graph schema ready' AS status FROM dual;
