-- Drop the table if it already exists (optional for a clean reset)
DROP TABLE if exists trivia_questions CASCADE CONSTRAINTS;

-- Create the trivia table
CREATE TABLE trivia_questions (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text VARCHAR2(500) NOT NULL,
    answer_text   VARCHAR2(200) NOT NULL,
    category      VARCHAR2(50)  DEFAULT 'Oracle History',
    difficulty    VARCHAR2(20)  DEFAULT 'Medium'
);

-- Insert Oracle history trivia
INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('In what year was the company that became Oracle founded?', '1977', 'Easy');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('What was Oracle''s original company name at founding in 1977?', 'Software Development Laboratories (SDL)', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Before it was called Oracle Corporation, what was the company''s name in 1979–1982?', 'Relational Software, Inc. (RSI)', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Oracle Database version "2" was the first commercial release. In what year did it ship?', '1979', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Name the three Oracle co-founders.', 'Larry Ellison; Bob Miner; Ed Oates', 'Easy');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Which Oracle Database major release introduced PL/SQL?', 'Oracle6', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Which release introduced Real Application Clusters (RAC)?', 'Oracle9i', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Oracle10g emphasized what computing model in its branding?', 'Grid computing', 'Easy');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Oracle12c introduced a new architecture for consolidation. What is it called?', 'Multitenant (CDB/PDB)', 'Easy');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Which company did Oracle acquire in 2010 that made it steward of Java and MySQL?', 'Sun Microsystems', 'Easy');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Exadata, Oracle’s engineered system for databases, debuted in what decade?', '2000s (2008)', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Oracle Autonomous Database was first announced in which year?', '2017', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Oracle Application Express (APEX) first launched under a different name. What was it?', 'HTML DB', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('What is the internal name for the relational engine that inspired Oracle''s original product name?', 'Oracle (from a CIA project codename)', 'Hard');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Oracle7 (early 1990s) became famous for which features (name one)?', 'Stored procedures, triggers, cost-based optimizer (any one)', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Which release family introduced Automatic Storage Management (ASM)?', 'Oracle10g', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Which release family introduced Active Data Guard?', 'Oracle11g', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('The first SQL*Net/Net8 predecessors enabled what key capability for Oracle databases?', 'Client/server network connectivity to the DB over protocols', 'Hard');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Oracle''s first relational database was heavily influenced by research from which IBM scientist?', 'Edgar F. Codd', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Which Oracle release name introduced the concept of "c" for cloud?', 'Oracle12c', 'Easy');

-- Save the data
COMMIT;
