-- Drop the table if it already exists (optional for a clean reset)
DROP TABLE if exists trivia_questions CASCADE CONSTRAINTS;

-- Create the trivia table
CREATE TABLE trivia_questions (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text VARCHAR2(500) NOT NULL,
    answer_text   VARCHAR2(200) NOT NULL,
    category      VARCHAR2(50)  DEFAULT 'Oracle History',
    difficulty    VARCHAR2(20)  DEFAULT 'Medium'
);

-- Insert Oracle history trivia
INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('In what year was the company that became Oracle founded?', '1977', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Which Oracle Database major release introduced PL/SQL?', 'Oracle 6', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Which release introduced Real Application Clusters (RAC)?', 'Oracle 9i', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Oracle 10g emphasized what computing model in its branding?', 'Grid computing', 'Easy');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Oracle 12c introduced a new architecture for consolidation. What is it called?', 'Multitenant (CDB/PDB)', 'Easy');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Which company did Oracle acquire in 2010 that made it steward of Java and MySQL?', 'Sun Microsystems', 'Easy');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Exadata, Oracle’s engineered system for databases, debuted in what decade?', '2000s (2008)', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Oracle Autonomous Database was first announced in which year?', '2017', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('What is the internal name for the relational engine that inspired Oracle''s original product name?', 'Oracle (from a CIA project codename)', 'Hard');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Who was Oracle''s first customer?', 'The CIA', 'Medium');

INSERT INTO trivia_questions (question_text, answer_text, difficulty) VALUES
('Which Oracle release name introduced the concept of "c" for cloud?', 'Oracle 12c', 'Easy');

-- Save the data
COMMIT;
